// SPDX-License-Identifier: Apache-2.0

// --- AIGER (ASCII) emitter.
// Allows exporting a `GateFn` into the standard "aag" format so that
// downstream tools such as the ABC synthesis/verification suite can ingest it.
//
// This intentionally mirrors the public surface of `emit_netlist.rs` albeit
// with a far simpler implementation: we only support purely combinational
// designs (no flops/latches) and do not yet emit the compact binary `aig`
// variant – only the human-readable `aag` dialect.
//
// The mapping from `GateFn` to AIGER is largely mechanical:
//
//   • Gate index 0 is the dedicated constant-false node that `GateBuilder`
//     always creates.  In AIGER the constant-false literal is 0 and constant
//     true is literal 1 (the complement of literal 0).
//   • Each `Input` bit becomes an AIGER input literal (non-negated).
//   • Each `AigNode::And2` becomes an AIGER AND definition line.
//   • Output literals are produced directly, taking into account operand
//     negation.
//
// ASCII and binary AIGER emission share the same canonical live-node ordering:
// inputs first, then AND nodes numbered by output-rooted post-order traversal.
// AND operands are ordered by descending emitted literal, matching the binary
// AIGER delta encoding requirement. This keeps heuristic downstream tools from
// seeing dialect-dependent graph presentations.
//
// INVARIANTS asserted throughout help catch accidental inconsistencies early
// while still compiling with `--release` (they become no-ops outside of debug
// builds).

use crate::aig::gate;
use crate::aig_serdes::canonical_aiger_layout::CanonicalAigerLayout;
use std::fmt::Write as _; // for write! macro on String // Needed for AigBitVector in tests

/// Emits the supplied `GateFn` into ASCII AIGER ("aag") format.
///
/// Returns the textual representation on success.
pub fn emit_aiger(gate_fn: &gate::GateFn, include_symbols: bool) -> Result<String, String> {
    // We only handle purely combinational circuits today.
    // Future work: support flops by mapping them onto AIGER latches.
    let latch_count = 0u32;
    let layout = CanonicalAigerLayout::new(gate_fn);

    let header = format!(
        "aag {} {} {} {} {}\n",
        layout.max_var_index, // M – maximum variable index referenced
        layout.input_count,   // I – #inputs
        latch_count,          // L – #latches (none)
        layout.output_count,  // O – #outputs
        layout.and_count      // A – #AND gates
    );

    let mut out =
        String::with_capacity(header.len() + 64 * (layout.input_count + layout.and_count) as usize);
    out.push_str(&header);

    // --- Inputs (one per line) ------------------------------------------------
    for input_index in 0..layout.input_count {
        write!(&mut out, "{}\n", (input_index + 1) << 1).unwrap();
    }

    // --- Latches (none) -------------------------------------------------------
    // Nothing to emit.

    // --- Outputs --------------------------------------------------------------
    for output in &gate_fn.outputs {
        for bit in output.bit_vector.iter_lsb_to_msb() {
            let lit = layout.operand_to_literal(gate_fn, *bit)?;
            write!(&mut out, "{}\n", lit).unwrap();
        }
    }

    // --- AND gates ------------------------------------------------------------
    for node_id in &layout.and_node_ids {
        let (lhs, rhs0, rhs1) = layout.sorted_and_literals(gate_fn, *node_id)?;
        write!(&mut out, "{} {} {}\n", lhs, rhs0, rhs1).unwrap();
    }

    if include_symbols {
        // --- Symbol table -----------------------------------------------------
        // Inputs first.
        let mut inp_idx = 0usize;
        for input in &gate_fn.inputs {
            let bit_cnt = input.bit_vector.get_bit_count();
            for bit_i in 0..bit_cnt {
                let name = if bit_cnt == 1 {
                    input.name.clone()
                } else {
                    format!("{}_{}", input.name, bit_i)
                };
                write!(&mut out, "i{} {}\n", inp_idx, name).unwrap();
                inp_idx += 1;
            }
        }

        // Outputs.
        let mut out_idx = 0usize;
        for output in &gate_fn.outputs {
            let bit_cnt = output.bit_vector.get_bit_count();
            for bit_i in 0..bit_cnt {
                let name = if bit_cnt == 1 {
                    output.name.clone()
                } else {
                    format!("{}_{}", output.name, bit_i)
                };
                write!(&mut out, "o{} {}\n", out_idx, name).unwrap();
                out_idx += 1;
            }
        }
    }

    // --- Comment section ------------------------------------------------------
    out.push_str("c\n");
    writeln!(out, "generated by xlsynth-g8r emit_aiger").unwrap();

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gate_builder::{GateBuilder, GateBuilderOptions};
    use pretty_assertions::assert_eq;

    #[test]
    fn test_emit_aiger_simple_and() {
        // Build: o = i0 & i1
        let mut gb = GateBuilder::new("and_fn".to_string(), GateBuilderOptions::no_opt());
        let i0 = gb.add_input("i0".to_string(), 1);
        let i1 = gb.add_input("i1".to_string(), 1);
        let and_out = gb.add_and_binary(*i0.get_lsb(0), *i1.get_lsb(0));
        gb.add_output("o".to_string(), gate::AigBitVector::from_bit(and_out));
        let gf = gb.build();

        let aiger = emit_aiger(&gf, true).unwrap();

        // Expected structure:
        //   - 2 inputs (ids 1,2)
        //   - 1 AND gate (id 3)
        //   - 1 output
        // Header: aag 3 2 0 1 1
        // Inputs: 2,4
        // Output: 6 (literal of id 3)
        // AND:    6 4 2
        // Symbols: i0, i1, o

        let expected = "aag 3 2 0 1 1\n2\n4\n6\n6 4 2\ni0 i0\ni1 i1\no0 o\nc\ngenerated by xlsynth-g8r emit_aiger\n";

        // Because symbol table ordering is deterministic, we can compare.
        assert_eq!(aiger, expected);
    }

    #[test]
    fn test_emit_aiger_uses_post_order_numbering() {
        let mut gb = GateBuilder::new("post_order_fn".to_string(), GateBuilderOptions::no_opt());
        let i0 = gb.add_input("i0".to_string(), 1);
        let i1 = gb.add_input("i1".to_string(), 1);
        let i2 = gb.add_input("i2".to_string(), 1);

        // Create the right-hand subtree first so GateFn creation order differs
        // from the output-rooted post-order that AIGER emission should expose.
        let right = gb.add_and_binary(*i1.get_lsb(0), *i2.get_lsb(0));
        let left = gb.add_and_binary(*i0.get_lsb(0), *i1.get_lsb(0));
        let root = gb.add_and_binary(left, right);
        gb.add_output("o".to_string(), gate::AigBitVector::from_bit(root));
        let gf = gb.build();

        let aiger = emit_aiger(&gf, false).unwrap();
        let expected = "aag 6 3 0 1 3\n2\n4\n6\n12\n8 4 2\n10 6 4\n12 10 8\nc\ngenerated by xlsynth-g8r emit_aiger\n";
        assert_eq!(aiger, expected);
    }
}
