// SPDX-License-Identifier: Apache-2.0

use std::collections::BTreeMap;
use std::io::Write;

use crate::Error;
use crate::Result;

#[derive(Debug, Clone)]
pub struct VcdWriter {
    timescale: String,
    vars: Vec<VcdVarDef>,
    name_to_id: BTreeMap<String, String>,
    last_values: BTreeMap<String, String>,
    cur_time: Option<u64>,
    wrote_header: bool,
}

#[derive(Debug, Clone)]
pub struct VcdVarDef {
    pub name: String, // fully-qualified
    pub width: u32,
    pub id: String,
}

impl VcdWriter {
    pub fn new(timescale: &str) -> Self {
        Self {
            timescale: timescale.to_string(),
            vars: Vec::new(),
            name_to_id: BTreeMap::new(),
            last_values: BTreeMap::new(),
            cur_time: None,
            wrote_header: false,
        }
    }

    pub fn add_var(&mut self, name: &str, width: u32) -> Result<()> {
        if self.name_to_id.contains_key(name) {
            return Err(Error::Parse(format!("duplicate VCD var: {name}")));
        }
        let id = make_id(self.vars.len());
        let def = VcdVarDef {
            name: name.to_string(),
            width,
            id: id.clone(),
        };
        self.name_to_id.insert(name.to_string(), id.clone());
        // Initialize last value to all x.
        let init = if width <= 1 {
            "x".to_string()
        } else {
            "x".repeat(width as usize)
        };
        self.last_values.insert(name.to_string(), init);
        self.vars.push(def);
        Ok(())
    }

    pub fn write_header<W: Write>(&mut self, mut w: W) -> Result<()> {
        if self.wrote_header {
            return Ok(());
        }

        writeln!(w, "$date\n  generated by xlsynth-vastly\n$end").map_err(map_io)?;
        writeln!(w, "$version\n  xlsynth-vastly\n$end").map_err(map_io)?;
        writeln!(w, "$timescale 1ns $end").map_err(map_io)?;
        let _ = &self.timescale; // reserved if we later want to vary

        // Emit scopes to match hierarchical names (e.g. tb.dut.q).
        let tree = ScopeNode::build(&self.vars)?;
        for (root_name, node) in tree.children {
            writeln!(w, "$scope module {} $end", root_name).map_err(map_io)?;
            node.emit(&mut w)?;
            writeln!(w, "$upscope $end").map_err(map_io)?;
        }
        writeln!(w, "$enddefinitions $end").map_err(map_io)?;
        writeln!(w, "$dumpvars").map_err(map_io)?;
        // Emit initial values (all x by default) so time 0 matches.
        for v in &self.vars {
            let init = self
                .last_values
                .get(&v.name)
                .cloned()
                .unwrap_or_else(|| "x".to_string());
            write_change(&mut w, v.width, &v.id, &init)?;
        }
        writeln!(w, "$end").map_err(map_io)?;
        self.wrote_header = true;
        Ok(())
    }

    pub fn change<W: Write>(
        &mut self,
        mut w: W,
        time: u64,
        name: &str,
        value_msb: &str,
    ) -> Result<()> {
        if !self.wrote_header {
            return Err(Error::Parse("VCD header not written".to_string()));
        }
        let id = self
            .name_to_id
            .get(name)
            .ok_or_else(|| Error::Parse(format!("unknown VCD var: {name}")))?;
        let width = self
            .vars
            .iter()
            .find(|v| v.name == name)
            .map(|v| v.width)
            .ok_or_else(|| Error::Parse(format!("unknown VCD var width: {name}")))?;

        let norm = normalize_bits(value_msb);
        let last = self.last_values.get(name).cloned().unwrap_or_default();
        if last == norm {
            return Ok(());
        }

        match self.cur_time {
            Some(t) if t == time => {}
            _ => {
                writeln!(w, "#{time}").map_err(map_io)?;
                self.cur_time = Some(time);
            }
        }

        write_change(&mut w, width, id, &norm)?;
        self.last_values.insert(name.to_string(), norm);
        Ok(())
    }
}

#[derive(Debug, Default, Clone)]
struct ScopeNode {
    vars: Vec<VcdVarDef>,
    children: BTreeMap<String, ScopeNode>,
}

impl ScopeNode {
    fn build(vars: &[VcdVarDef]) -> Result<ScopeNode> {
        let mut root = ScopeNode::default();
        for v in vars {
            let (scopes, leaf) = split_scopes(&v.name)?;
            let mut cur = &mut root;
            for s in scopes {
                cur = cur.children.entry(s).or_default();
            }
            let mut vv = v.clone();
            vv.name = leaf; // store leaf ref for $var line
            cur.vars.push(vv);
        }
        Ok(root)
    }

    fn emit<W: Write>(&self, w: &mut W) -> Result<()> {
        for v in &self.vars {
            writeln!(w, "$var wire {} {} {} $end", v.width, v.id, v.name).map_err(map_io)?;
        }
        for (child_name, child) in &self.children {
            writeln!(w, "$scope module {} $end", child_name).map_err(map_io)?;
            child.emit(w)?;
            writeln!(w, "$upscope $end").map_err(map_io)?;
        }
        Ok(())
    }
}

fn split_scopes(full: &str) -> Result<(Vec<String>, String)> {
    let parts: Vec<&str> = full.split('.').collect();
    if parts.len() < 2 {
        return Err(Error::Parse(format!(
            "VCD var name must be hierarchical (got {full})"
        )));
    }
    let scopes = parts[..parts.len() - 1]
        .iter()
        .map(|s| (*s).to_string())
        .collect();
    let leaf = parts[parts.len() - 1].to_string();
    Ok((scopes, leaf))
}

fn make_id(mut n: usize) -> String {
    // Generate a printable id using base-94 ASCII from '!'..'~'.
    const BASE: usize = 94;
    const FIRST: u8 = b'!';
    let mut out = Vec::new();
    loop {
        let d = (n % BASE) as u8;
        out.push((FIRST + d) as char);
        n /= BASE;
        if n == 0 {
            break;
        }
    }
    out.into_iter().collect()
}

fn write_change<W: Write>(w: &mut W, width: u32, id: &str, value_msb: &str) -> Result<()> {
    if width <= 1 {
        let ch = value_msb.chars().next().unwrap_or('x');
        writeln!(w, "{ch}{id}").map_err(map_io)?;
        return Ok(());
    }
    writeln!(w, "b{} {}", value_msb, id).map_err(map_io)?;
    Ok(())
}

fn normalize_bits(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '0' => '0',
            '1' => '1',
            'x' | 'X' => 'x',
            'z' | 'Z' => 'z',
            _ => 'x',
        })
        .collect()
}

fn map_io(e: std::io::Error) -> Error {
    Error::Parse(format!("io error: {e}"))
}
