// SPDX-License-Identifier: Apache-2.0

use std::collections::BTreeSet;

use crate::Error;
use crate::Result;
use crate::vcd::Vcd;

#[derive(Debug, Clone)]
pub struct VcdDiffOptions {
    pub require_same_timescale: bool,
}

impl Default for VcdDiffOptions {
    fn default() -> Self {
        Self {
            require_same_timescale: true,
        }
    }
}

pub fn diff_vcd_exact(a: &Vcd, b: &Vcd, opts: &VcdDiffOptions) -> Result<()> {
    if opts.require_same_timescale && a.timescale != b.timescale {
        return Err(Error::Parse(format!(
            "timescale mismatch: a={:?} b={:?}",
            a.timescale, b.timescale
        )));
    }

    let av: BTreeSet<String> = a.var_names();
    let bv: BTreeSet<String> = b.var_names();
    if av != bv {
        let only_a: Vec<String> = av.difference(&bv).cloned().collect();
        let only_b: Vec<String> = bv.difference(&av).cloned().collect();
        return Err(Error::Parse(format!(
            "var set mismatch: only_a={only_a:?} only_b={only_b:?}"
        )));
    }

    let at = a.times();
    let bt = b.times();
    if at != bt {
        return Err(Error::Parse(format!(
            "timestamp list mismatch: a={at:?} b={bt:?}"
        )));
    }

    let am = a.materialize()?;
    let bm = b.materialize()?;
    if am.len() != bm.len() {
        return Err(Error::Parse("materialized length mismatch".to_string()));
    }
    for i in 0..am.len() {
        let (ta, va) = &am[i];
        let (tb, vb) = &bm[i];
        if ta != tb {
            return Err(Error::Parse(format!(
                "time mismatch at idx {i}: a={ta} b={tb}"
            )));
        }
        if va != vb {
            let mut diffs: Vec<(String, String, String)> = Vec::new();
            for name in va.keys() {
                let avv = va.get(name).cloned().unwrap_or_default();
                let bvv = vb.get(name).cloned().unwrap_or_default();
                if avv != bvv {
                    diffs.push((name.clone(), avv, bvv));
                    if diffs.len() >= 10 {
                        break;
                    }
                }
            }
            return Err(Error::Parse(format!(
                "value mismatch at time {ta}: first_diffs={diffs:?}"
            )));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn diff_ignores_date_and_version_blocks() {
        let a_text = r#"
$date
  generated by xlsynth-vastly
$end
$version
  xlsynth-vastly
$end
$timescale 1ns $end
$scope module tb $end
$var wire 1 ! sig $end
$upscope $end
$enddefinitions $end
$dumpvars
x!
$end
#0
0!
#1
1!
"#;

        let b_text = r#"
$date
  generated by iverilog
$end
$version
  Icarus Verilog
$end
$timescale 1ns $end
$scope module tb $end
$var wire 1 ! sig $end
$upscope $end
$enddefinitions $end
$dumpvars
x!
$end
#0
0!
#1
1!
"#;

        let a = Vcd::parse(a_text).unwrap();
        let b = Vcd::parse(b_text).unwrap();
        diff_vcd_exact(&a, &b, &VcdDiffOptions::default()).unwrap();
    }
}
