// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "duplicate_widget".

pub use xlsynth_aot_runtime::{AotArtifactMetadata, AotError, AotRunResult, SBits, UBits};
#[allow(unused_imports)]
use xlsynth_aot_runtime::{
    read_leaf_element, write_leaf_element, AotElementLayout, AotRunnerLayout,
    StandaloneRunner,
};
pub mod bar {
    pub mod widget {
        #![allow(dead_code)]
        #![allow(unused_imports)]
        use super::super::{
            read_leaf_element, write_leaf_element, AotArtifactMetadata, AotElementLayout,
            AotError, AotRunResult, AotRunnerLayout, SBits, StandaloneRunner, UBits,
        };
        #[derive(Debug, Clone, PartialEq, Eq)]
        pub struct Widget {
            pub widget_id: UBits<8>,
        }
    }
}
pub mod foo {
    pub mod widget {
        #![allow(dead_code)]
        #![allow(unused_imports)]
        use super::super::{
            read_leaf_element, write_leaf_element, AotArtifactMetadata, AotElementLayout,
            AotError, AotRunResult, AotRunnerLayout, SBits, StandaloneRunner, UBits,
        };
        #[derive(Debug, Clone, PartialEq, Eq)]
        pub struct Widget {
            pub widget_id: UBits<8>,
        }
    }
}
pub mod frobber {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use super::{
        read_leaf_element, write_leaf_element, AotArtifactMetadata, AotElementLayout,
        AotError, AotRunResult, AotRunnerLayout, SBits, StandaloneRunner, UBits,
    };
    unsafe extern "C" {
        #[link_name = "__xlsynth_standalone_duplicate_widget"]
        fn __xlsynth_aot_linked_symbol_duplicate_widget();
    }
    const INPUT_BUFFER_SIZES: &[usize] = &[1];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[1];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];
    const RUNNER_LAYOUT: AotRunnerLayout = AotRunnerLayout {
        input_buffer_sizes: INPUT_BUFFER_SIZES,
        input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS,
        output_buffer_sizes: OUTPUT_BUFFER_SIZES,
        output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS,
        temp_buffer_size: 0,
        temp_buffer_alignment: 1,
    };
    /// Runtime-visible metadata for the generated standalone artifact.
    pub const ARTIFACT_METADATA: AotArtifactMetadata = AotArtifactMetadata {
        abi_version: 1,
        entrypoint_symbol: "__xlsynth_standalone_duplicate_widget",
        has_asserts: false,
        has_traces: false,
    };
    const INPUT0_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const OUTPUT0_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
    ];
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(
        _value: &super::foo::widget::Widget,
        dst: &mut [u8],
    ) -> Result<(), AotError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).widget_id).to_le_bytes()?;
        write_leaf_element(dst, &INPUT0_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT0_LAYOUT.len(), 1);
        Ok(())
    }
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<super::bar::widget::Widget, AotError> {
        debug_assert_eq!(src.len(), 1);
        let mut decoded_bytes_0 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize], &mut decoded_bytes_0);
        let decoded_value_1 = UBits::<8>::from_le_bytes(&decoded_bytes_0)?;
        let decoded_value_2 = super::bar::widget::Widget {
            widget_id: decoded_value_1,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 1);
        Ok(decoded_value_2)
    }
    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the standalone ABI buffers; create one runner per
    /// concurrent caller instead of sharing it across threads.
    pub struct Runner {
        inner: StandaloneRunner,
    }
    impl Runner {
        /// Creates a reusable runner for the generated typed DSLX entrypoint.
        ///
        /// # Errors
        ///
        /// Returns an error if the standalone artifact metadata cannot initialize
        /// an AOT runner.
        pub fn new() -> Result<Self, AotError> {
            Ok(Self {
                inner: unsafe {
                    StandaloneRunner::new(
                        &ARTIFACT_METADATA,
                        __xlsynth_aot_linked_symbol_duplicate_widget as *const (),
                        &RUNNER_LAYOUT,
                    )?
                },
            })
        }
        /// Runs the entrypoint and returns the output together with assertion
        /// events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            widget: &super::foo::widget::Widget,
        ) -> Result<AotRunResult<super::bar::widget::Widget>, AotError> {
            encode_input_0(widget, self.inner.input_mut(0))?;
            self.inner.run_raw();
            Ok(AotRunResult {
                output: decode_output_0(self.inner.output(0))?,
                assert_messages: self.inner.assert_messages().to_vec(),
            })
        }
        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, output decoding, or
        /// an XLS assertion fails.
        pub fn run(
            &mut self,
            widget: &super::foo::widget::Widget,
        ) -> Result<super::bar::widget::Widget, AotError> {
            encode_input_0(widget, self.inner.input_mut(0))?;
            self.inner.run_raw();
            if let Some(first_assertion) = self.inner.assert_messages().first() {
                return Err(AotError(format!("XLS assertion failed: {first_assertion}")));
            }
            decode_output_0(self.inner.output(0))
        }
    }
    /// Creates a reusable runner for the generated typed DSLX entrypoint.
    pub fn new_runner() -> Result<Runner, AotError> {
        Runner::new()
    }
}
