// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "parametric_shapes".

pub use xlsynth_aot_runtime::{AotArtifactMetadata, AotError, AotRunResult, SBits, UBits};
#[allow(unused_imports)]
use xlsynth_aot_runtime::{
    read_leaf_element, write_leaf_element, AotElementLayout, AotRunnerLayout,
    StandaloneRunner,
};
pub mod parametric_shapes {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use super::{
        read_leaf_element, write_leaf_element, AotArtifactMetadata, AotElementLayout,
        AotError, AotRunResult, AotRunnerLayout, SBits, StandaloneRunner, UBits,
    };
    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Box__N_8 {
        pub value: UBits<8>,
    }
    pub type Box8 = Box__N_8;
    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Box__N_16 {
        pub value: UBits<16>,
    }
    pub type Box16 = Box__N_16;
    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Matrix__R_2__C_3 {
        pub rows: [[UBits<8>; 3]; 2],
    }
    pub type Matrix2x3 = Matrix__R_2__C_3;
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParametricShapesResult {
        pub box8: Box8,
        pub box16: Box16,
        pub matrix: Matrix2x3,
    }
    unsafe extern "C" {
        #[link_name = "__xlsynth_standalone_parametric_shapes"]
        fn __xlsynth_aot_linked_symbol_parametric_shapes();
    }
    const INPUT_BUFFER_SIZES: &[usize] = &[1, 2, 6];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8, 8, 8];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[10];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];
    const RUNNER_LAYOUT: AotRunnerLayout = AotRunnerLayout {
        input_buffer_sizes: INPUT_BUFFER_SIZES,
        input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS,
        output_buffer_sizes: OUTPUT_BUFFER_SIZES,
        output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS,
        temp_buffer_size: 0,
        temp_buffer_alignment: 1,
    };
    /// Runtime-visible metadata for the generated standalone artifact.
    pub const ARTIFACT_METADATA: AotArtifactMetadata = AotArtifactMetadata {
        abi_version: 1,
        entrypoint_symbol: "__xlsynth_standalone_parametric_shapes",
        has_asserts: false,
        has_traces: false,
    };
    const INPUT0_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const INPUT1_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 2,
            padded_size: 2,
        },
    ];
    const INPUT2_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 5,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const OUTPUT0_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 2,
            data_size: 2,
            padded_size: 2,
        },
        AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 5,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 6,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 7,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 8,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 9,
            data_size: 1,
            padded_size: 1,
        },
    ];
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(_value: &Box8, dst: &mut [u8]) -> Result<(), AotError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).value).to_le_bytes()?;
        write_leaf_element(dst, &INPUT0_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT0_LAYOUT.len(), 1);
        Ok(())
    }
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_1(_value: &Box16, dst: &mut [u8]) -> Result<(), AotError> {
        debug_assert_eq!(dst.len(), 2);
        dst.fill(0);
        let encoded_bytes = ((*_value).value).to_le_bytes()?;
        write_leaf_element(dst, &INPUT1_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT1_LAYOUT.len(), 1);
        Ok(())
    }
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_2(_value: &Matrix2x3, dst: &mut [u8]) -> Result<(), AotError> {
        debug_assert_eq!(dst.len(), 6);
        dst.fill(0);
        for index_0 in 0..2 {
            for index_1 in 0..3 {
                let encoded_bytes = ((((*_value).rows)[index_0])[index_1])
                    .to_le_bytes()?;
                write_leaf_element(
                    dst,
                    &INPUT2_LAYOUT[0usize + index_0 * 3 + index_1],
                    &encoded_bytes,
                );
            }
        }
        debug_assert_eq!(INPUT2_LAYOUT.len(), 6);
        Ok(())
    }
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<ParametricShapesResult, AotError> {
        debug_assert_eq!(src.len(), 10);
        let mut decoded_bytes_0 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize], &mut decoded_bytes_0);
        let decoded_value_1 = UBits::<8>::from_le_bytes(&decoded_bytes_0)?;
        let decoded_value_2 = Box8 { value: decoded_value_1 };
        let mut decoded_bytes_3 = vec![0u8; 2];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize + 1], &mut decoded_bytes_3);
        let decoded_value_4 = UBits::<16>::from_le_bytes(&decoded_bytes_3)?;
        let decoded_value_5 = Box16 { value: decoded_value_4 };
        let mut decoded_items_7 = Vec::with_capacity(2);
        for index_0 in 0..2 {
            let mut decoded_items_9 = Vec::with_capacity(3);
            for index_1 in 0..3 {
                let mut decoded_bytes_10 = vec![0u8; 1];
                read_leaf_element(
                    src,
                    &OUTPUT0_LAYOUT[0usize + 2 + index_0 * 3 + index_1],
                    &mut decoded_bytes_10,
                );
                let decoded_value_11 = UBits::<8>::from_le_bytes(&decoded_bytes_10)?;
                decoded_items_9.push(decoded_value_11);
            }
            let decoded_value_8: [UBits<8>; 3] = match std::convert::TryInto::try_into(
                decoded_items_9,
            ) {
                Ok(value) => value,
                Err(values) => {
                    return Err(
                        AotError(
                            format!(
                                "AOT decode internal error: expected 3 array elements, got {}",
                                values.len()
                            ),
                        ),
                    );
                }
            };
            decoded_items_7.push(decoded_value_8);
        }
        let decoded_value_6: [[UBits<8>; 3]; 2] = match std::convert::TryInto::try_into(
            decoded_items_7,
        ) {
            Ok(value) => value,
            Err(values) => {
                return Err(
                    AotError(
                        format!(
                            "AOT decode internal error: expected 2 array elements, got {}",
                            values.len()
                        ),
                    ),
                );
            }
        };
        let decoded_value_12 = Matrix2x3 { rows: decoded_value_6 };
        let decoded_value_13 = ParametricShapesResult {
            box8: decoded_value_2,
            box16: decoded_value_5,
            matrix: decoded_value_12,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 8);
        Ok(decoded_value_13)
    }
    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the standalone ABI buffers; create one runner per
    /// concurrent caller instead of sharing it across threads.
    pub struct Runner {
        inner: StandaloneRunner,
    }
    impl Runner {
        /// Creates a reusable runner for the generated typed DSLX entrypoint.
        ///
        /// # Errors
        ///
        /// Returns an error if the standalone artifact metadata cannot initialize
        /// an AOT runner.
        pub fn new() -> Result<Self, AotError> {
            Ok(Self {
                inner: unsafe {
                    StandaloneRunner::new(
                        &ARTIFACT_METADATA,
                        __xlsynth_aot_linked_symbol_parametric_shapes as *const (),
                        &RUNNER_LAYOUT,
                    )?
                },
            })
        }
        /// Runs the entrypoint and returns the output together with assertion
        /// events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            box8: &Box8,
            box16: &Box16,
            matrix: &Matrix2x3,
        ) -> Result<AotRunResult<ParametricShapesResult>, AotError> {
            encode_input_0(box8, self.inner.input_mut(0))?;
            encode_input_1(box16, self.inner.input_mut(1))?;
            encode_input_2(matrix, self.inner.input_mut(2))?;
            self.inner.run_raw();
            Ok(AotRunResult {
                output: decode_output_0(self.inner.output(0))?,
                assert_messages: self.inner.assert_messages().to_vec(),
            })
        }
        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, output decoding, or
        /// an XLS assertion fails.
        pub fn run(
            &mut self,
            box8: &Box8,
            box16: &Box16,
            matrix: &Matrix2x3,
        ) -> Result<ParametricShapesResult, AotError> {
            encode_input_0(box8, self.inner.input_mut(0))?;
            encode_input_1(box16, self.inner.input_mut(1))?;
            encode_input_2(matrix, self.inner.input_mut(2))?;
            self.inner.run_raw();
            if let Some(first_assertion) = self.inner.assert_messages().first() {
                return Err(AotError(format!("XLS assertion failed: {first_assertion}")));
            }
            decode_output_0(self.inner.output(0))
        }
    }
    /// Creates a reusable runner for the generated typed DSLX entrypoint.
    pub fn new_runner() -> Result<Runner, AotError> {
        Runner::new()
    }
}
