// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "parametric_imports".

pub mod parametric_imports {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use xlsynth::{IrSBits, IrUBits, IrValue};

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum LocalMode {
        Idle = 0,
        Busy = 1,
    }

    impl From<LocalMode> for IrValue {
        fn from(value: LocalMode) -> Self {
            match value {
                LocalMode::Idle => IrValue::make_ubits(2, 0).unwrap(),
                LocalMode::Busy => IrValue::make_ubits(2, 1).unwrap(),
            }
        }
    }

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Box__N_8 {
        pub value: IrUBits<8>,
    }

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Mixed__N_4 {
        pub mode: LocalMode,
        pub remote: super::parametric_lib::RemotePlain,
        pub nested: [[IrUBits<8>; 4]; 2],
        pub boxes: [Box__N_8; 2],
    }

    pub type Mixed4 = Mixed__N_4;

    pub type ImportedAlias = super::parametric_lib::RemoteBox8;

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParametricImportsResult {
        pub mixed: Mixed4,
        pub imported_alias: ImportedAlias,
    }

    unsafe extern "C" {
        #[link_name = "__parametric_imports__exercise_parametric_imports"]
        fn __xlsynth_aot_linked_symbol_parametric_imports();
    }

    const ENTRYPOINTS_PROTO: &[u8] = include_bytes!("parametric_imports.entrypoints.pb");
    const INPUT_BUFFER_SIZES: &[usize] = &[12, 1];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8, 8];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[13];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];

    const INPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 5,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 6,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 7,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 8,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 9,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 10,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 11,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const INPUT1_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] =
        &[xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        }];
    const OUTPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 5,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 6,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 7,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 8,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 9,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 10,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 11,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 12,
            data_size: 1,
            padded_size: 1,
        },
    ];

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(_value: &Mixed4, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 12);
        dst.fill(0);
        let encoded_value: u64 = match (*_value).mode {
            LocalMode::Idle => 0,
            LocalMode::Busy => 1,
        };
        let encoded_bits = xlsynth::IrUBits::<2>::from_u64(encoded_value)?;
        let encoded_bytes = encoded_bits.to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize], &encoded_bytes);
        let encoded_bytes = (((*_value).remote).id).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 1], &encoded_bytes);
        for index_0 in 0..2 {
            for index_1 in 0..4 {
                let encoded_bytes = ((((*_value).nested)[index_0])[index_1]).to_le_bytes()?;
                xlsynth::aot_runner::write_leaf_element(
                    dst,
                    &INPUT0_LAYOUT[0usize + 2 + index_0 * 4 + index_1],
                    &encoded_bytes,
                );
            }
        }
        for index_2 in 0..2 {
            let encoded_bytes = ((((*_value).boxes)[index_2]).value).to_le_bytes()?;
            xlsynth::aot_runner::write_leaf_element(
                dst,
                &INPUT0_LAYOUT[0usize + 10 + index_2],
                &encoded_bytes,
            );
        }
        debug_assert_eq!(INPUT0_LAYOUT.len(), 12);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_1(_value: &ImportedAlias, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).value).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT1_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT1_LAYOUT.len(), 1);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<ParametricImportsResult, xlsynth::XlsynthError> {
        debug_assert_eq!(src.len(), 13);
        let mut decoded_bytes_0 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(src, &OUTPUT0_LAYOUT[0usize], &mut decoded_bytes_0);
        let decoded_bits_1 = xlsynth::IrUBits::<2>::from_le_bytes(&decoded_bytes_0)?;
        let decoded_scalar_2 = decoded_bits_1.to_u64()?;
        let decoded_value_3 = match decoded_scalar_2 {
            0 => LocalMode::Idle,
            1 => LocalMode::Busy,
            value => {
                return Err(xlsynth::XlsynthError(format!(
                    "AOT decode invalid enum value {value} for LocalMode"
                )))
            }
        };
        let mut decoded_bytes_4 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 1],
            &mut decoded_bytes_4,
        );
        let decoded_value_5 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_4)?;
        let decoded_value_6 = super::parametric_lib::RemotePlain {
            id: decoded_value_5,
        };
        let mut decoded_items_8 = Vec::with_capacity(2);
        for index_0 in 0..2 {
            let mut decoded_items_10 = Vec::with_capacity(4);
            for index_1 in 0..4 {
                let mut decoded_bytes_11 = vec![0u8; 1];
                xlsynth::aot_runner::read_leaf_element(
                    src,
                    &OUTPUT0_LAYOUT[0usize + 2 + index_0 * 4 + index_1],
                    &mut decoded_bytes_11,
                );
                let decoded_value_12 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_11)?;
                decoded_items_10.push(decoded_value_12);
            }
            let decoded_value_9: [IrUBits<8>; 4] =
                match std::convert::TryInto::try_into(decoded_items_10) {
                    Ok(value) => value,
                    Err(values) => {
                        return Err(xlsynth::XlsynthError(format!(
                            "AOT decode internal error: expected 4 array elements, got {}",
                            values.len()
                        )))
                    }
                };
            decoded_items_8.push(decoded_value_9);
        }
        let decoded_value_7: [[IrUBits<8>; 4]; 2] =
            match std::convert::TryInto::try_into(decoded_items_8) {
                Ok(value) => value,
                Err(values) => {
                    return Err(xlsynth::XlsynthError(format!(
                        "AOT decode internal error: expected 2 array elements, got {}",
                        values.len()
                    )))
                }
            };
        let mut decoded_items_14 = Vec::with_capacity(2);
        for index_2 in 0..2 {
            let mut decoded_bytes_15 = vec![0u8; 1];
            xlsynth::aot_runner::read_leaf_element(
                src,
                &OUTPUT0_LAYOUT[0usize + 10 + index_2],
                &mut decoded_bytes_15,
            );
            let decoded_value_16 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_15)?;
            let decoded_value_17 = Box__N_8 {
                value: decoded_value_16,
            };
            decoded_items_14.push(decoded_value_17);
        }
        let decoded_value_13: [Box__N_8; 2] =
            match std::convert::TryInto::try_into(decoded_items_14) {
                Ok(value) => value,
                Err(values) => {
                    return Err(xlsynth::XlsynthError(format!(
                        "AOT decode internal error: expected 2 array elements, got {}",
                        values.len()
                    )))
                }
            };
        let decoded_value_18 = Mixed4 {
            mode: decoded_value_3,
            remote: decoded_value_6,
            nested: decoded_value_7,
            boxes: decoded_value_13,
        };
        let mut decoded_bytes_19 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 12],
            &mut decoded_bytes_19,
        );
        let decoded_value_20 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_19)?;
        let decoded_value_21 = ImportedAlias {
            value: decoded_value_20,
        };
        let decoded_value_22 = ParametricImportsResult {
            mixed: decoded_value_18,
            imported_alias: decoded_value_21,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 13);
        Ok(decoded_value_22)
    }

    pub fn descriptor() -> xlsynth::AotEntrypointDescriptor<'static> {
        unsafe {
            xlsynth::AotEntrypointDescriptor::from_raw_parts_unchecked(
                ENTRYPOINTS_PROTO,
                __xlsynth_aot_linked_symbol_parametric_imports as *const () as usize,
                xlsynth::AotEntrypointMetadata {
                    symbol: "__parametric_imports__exercise_parametric_imports".to_string(),
                    input_buffer_sizes: INPUT_BUFFER_SIZES.to_vec(),
                    input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS.to_vec(),
                    output_buffer_sizes: OUTPUT_BUFFER_SIZES.to_vec(),
                    output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS.to_vec(),
                    temp_buffer_size: 0,
                    temp_buffer_alignment: 1,
                },
            )
        }
    }

    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the ABI buffers owned by `xlsynth::AotRunner`; create
    /// one runner per concurrent caller instead of sharing it across
    /// threads.
    pub struct Runner {
        inner: xlsynth::AotRunner<'static>,
    }

    impl Runner {
        /// # Errors
        ///
        /// Returns an error if the descriptor metadata cannot initialize an AOT
        /// runner.
        pub fn new() -> Result<Self, xlsynth::XlsynthError> {
            Ok(Self {
                inner: xlsynth::AotRunner::new(descriptor())?,
            })
        }

        /// Runs the entrypoint and returns the output together with
        /// trace/assert events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            mixed: &Mixed4,
            imported_alias: &ImportedAlias,
        ) -> Result<xlsynth::AotRunResult<ParametricImportsResult>, xlsynth::XlsynthError> {
            encode_input_0(mixed, self.inner.input_mut(0))?;
            encode_input_1(imported_alias, self.inner.input_mut(1))?;
            let result = self
                .inner
                .run_with_events(|inner| decode_output_0(inner.output(0)))?;
            Ok(xlsynth::AotRunResult {
                output: result.output?,
                trace_messages: result.trace_messages,
                assert_messages: result.assert_messages,
            })
        }

        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run(
            &mut self,
            mixed: &Mixed4,
            imported_alias: &ImportedAlias,
        ) -> Result<ParametricImportsResult, xlsynth::XlsynthError> {
            encode_input_0(mixed, self.inner.input_mut(0))?;
            encode_input_1(imported_alias, self.inner.input_mut(1))?;
            self.inner.run()?;
            decode_output_0(self.inner.output(0))
        }
    }

    pub fn new_runner() -> Result<Runner, xlsynth::XlsynthError> {
        Runner::new()
    }
}

pub mod parametric_lib {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use xlsynth::{IrSBits, IrUBits, IrValue};

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct RemotePlain {
        pub id: IrUBits<8>,
    }

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct RemoteBox__N_8 {
        pub value: IrUBits<8>,
    }

    pub type RemoteBox8 = RemoteBox__N_8;
}
