// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "parametric_values".

pub use xlsynth_aot_runtime::{AotArtifactMetadata, AotError, AotRunResult, SBits, UBits};
#[allow(unused_imports)]
use xlsynth_aot_runtime::{
    read_leaf_element, write_leaf_element, AotElementLayout, AotRunnerLayout,
    StandaloneRunner,
};
pub mod parametric_values {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use super::{
        read_leaf_element, write_leaf_element, AotArtifactMetadata, AotElementLayout,
        AotError, AotRunResult, AotRunnerLayout, SBits, StandaloneRunner, UBits,
    };
    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ExprBox__N_8 {
        pub value: UBits<8>,
    }
    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct SignedTag__S_m3 {
        pub payload: UBits<8>,
    }
    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct WideTag__W_18446744073709551616 {
        pub payload: UBits<8>,
    }
    pub type ExprBox8 = ExprBox__N_8;
    pub type NegativeTag = SignedTag__S_m3;
    pub type HugeTag = WideTag__W_18446744073709551616;
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParametricValuesResult {
        pub expr_box: ExprBox8,
        pub negative: NegativeTag,
        pub huge: HugeTag,
    }
    unsafe extern "C" {
        #[link_name = "__xlsynth_standalone_parametric_values"]
        fn __xlsynth_aot_linked_symbol_parametric_values();
    }
    const INPUT_BUFFER_SIZES: &[usize] = &[1, 1, 1];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8, 8, 8];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[3];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];
    const RUNNER_LAYOUT: AotRunnerLayout = AotRunnerLayout {
        input_buffer_sizes: INPUT_BUFFER_SIZES,
        input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS,
        output_buffer_sizes: OUTPUT_BUFFER_SIZES,
        output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS,
        temp_buffer_size: 0,
        temp_buffer_alignment: 1,
    };
    /// Runtime-visible metadata for the generated standalone artifact.
    pub const ARTIFACT_METADATA: AotArtifactMetadata = AotArtifactMetadata {
        abi_version: 1,
        entrypoint_symbol: "__xlsynth_standalone_parametric_values",
        has_asserts: false,
        has_traces: false,
    };
    const INPUT0_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const INPUT1_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const INPUT2_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const OUTPUT0_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
    ];
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(_value: &ExprBox8, dst: &mut [u8]) -> Result<(), AotError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).value).to_le_bytes()?;
        write_leaf_element(dst, &INPUT0_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT0_LAYOUT.len(), 1);
        Ok(())
    }
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_1(_value: &NegativeTag, dst: &mut [u8]) -> Result<(), AotError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).payload).to_le_bytes()?;
        write_leaf_element(dst, &INPUT1_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT1_LAYOUT.len(), 1);
        Ok(())
    }
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_2(_value: &HugeTag, dst: &mut [u8]) -> Result<(), AotError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).payload).to_le_bytes()?;
        write_leaf_element(dst, &INPUT2_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT2_LAYOUT.len(), 1);
        Ok(())
    }
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<ParametricValuesResult, AotError> {
        debug_assert_eq!(src.len(), 3);
        let mut decoded_bytes_0 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize], &mut decoded_bytes_0);
        let decoded_value_1 = UBits::<8>::from_le_bytes(&decoded_bytes_0)?;
        let decoded_value_2 = ExprBox8 { value: decoded_value_1 };
        let mut decoded_bytes_3 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize + 1], &mut decoded_bytes_3);
        let decoded_value_4 = UBits::<8>::from_le_bytes(&decoded_bytes_3)?;
        let decoded_value_5 = NegativeTag {
            payload: decoded_value_4,
        };
        let mut decoded_bytes_6 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize + 2], &mut decoded_bytes_6);
        let decoded_value_7 = UBits::<8>::from_le_bytes(&decoded_bytes_6)?;
        let decoded_value_8 = HugeTag {
            payload: decoded_value_7,
        };
        let decoded_value_9 = ParametricValuesResult {
            expr_box: decoded_value_2,
            negative: decoded_value_5,
            huge: decoded_value_8,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 3);
        Ok(decoded_value_9)
    }
    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the standalone ABI buffers; create one runner per
    /// concurrent caller instead of sharing it across threads.
    pub struct Runner {
        inner: StandaloneRunner,
    }
    impl Runner {
        /// Creates a reusable runner for the generated typed DSLX entrypoint.
        ///
        /// # Errors
        ///
        /// Returns an error if the standalone artifact metadata cannot initialize
        /// an AOT runner.
        pub fn new() -> Result<Self, AotError> {
            Ok(Self {
                inner: unsafe {
                    StandaloneRunner::new(
                        &ARTIFACT_METADATA,
                        __xlsynth_aot_linked_symbol_parametric_values as *const (),
                        &RUNNER_LAYOUT,
                    )?
                },
            })
        }
        /// Runs the entrypoint and returns the output together with assertion
        /// events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            expr_box: &ExprBox8,
            negative: &NegativeTag,
            huge: &HugeTag,
        ) -> Result<AotRunResult<ParametricValuesResult>, AotError> {
            encode_input_0(expr_box, self.inner.input_mut(0))?;
            encode_input_1(negative, self.inner.input_mut(1))?;
            encode_input_2(huge, self.inner.input_mut(2))?;
            self.inner.run_raw();
            Ok(AotRunResult {
                output: decode_output_0(self.inner.output(0))?,
                assert_messages: self.inner.assert_messages().to_vec(),
            })
        }
        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, output decoding, or
        /// an XLS assertion fails.
        pub fn run(
            &mut self,
            expr_box: &ExprBox8,
            negative: &NegativeTag,
            huge: &HugeTag,
        ) -> Result<ParametricValuesResult, AotError> {
            encode_input_0(expr_box, self.inner.input_mut(0))?;
            encode_input_1(negative, self.inner.input_mut(1))?;
            encode_input_2(huge, self.inner.input_mut(2))?;
            self.inner.run_raw();
            if let Some(first_assertion) = self.inner.assert_messages().first() {
                return Err(AotError(format!("XLS assertion failed: {first_assertion}")));
            }
            decode_output_0(self.inner.output(0))
        }
    }
    /// Creates a reusable runner for the generated typed DSLX entrypoint.
    pub fn new_runner() -> Result<Runner, AotError> {
        Runner::new()
    }
}
