// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "parametric_values".

pub mod parametric_values {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use xlsynth::{IrSBits, IrUBits, IrValue};

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ExprBox__N_8 {
        pub value: IrUBits<8>,
    }

    pub type ExprBox8 = ExprBox__N_8;

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct SignedTag__S_m3 {
        pub payload: IrUBits<8>,
    }

    pub type NegativeTag = SignedTag__S_m3;

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct WideTag__W_18446744073709551616 {
        pub payload: IrUBits<8>,
    }

    pub type HugeTag = WideTag__W_18446744073709551616;

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParametricValuesResult {
        pub expr_box: ExprBox8,
        pub negative: NegativeTag,
        pub huge: HugeTag,
    }

    unsafe extern "C" {
        #[link_name = "__parametric_values__exercise_parametric_values"]
        fn __xlsynth_aot_linked_symbol_parametric_values();
    }

    const ENTRYPOINTS_PROTO: &[u8] = include_bytes!("parametric_values.entrypoints.pb");
    const INPUT_BUFFER_SIZES: &[usize] = &[1, 1, 1];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8, 8, 8];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[3];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];

    const INPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] =
        &[xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        }];
    const INPUT1_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] =
        &[xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        }];
    const INPUT2_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] =
        &[xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        }];
    const OUTPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
    ];

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(_value: &ExprBox8, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).value).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT0_LAYOUT.len(), 1);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_1(_value: &NegativeTag, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).payload).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT1_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT1_LAYOUT.len(), 1);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_2(_value: &HugeTag, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).payload).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT2_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT2_LAYOUT.len(), 1);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<ParametricValuesResult, xlsynth::XlsynthError> {
        debug_assert_eq!(src.len(), 3);
        let mut decoded_bytes_0 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(src, &OUTPUT0_LAYOUT[0usize], &mut decoded_bytes_0);
        let decoded_value_1 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_0)?;
        let decoded_value_2 = ExprBox8 {
            value: decoded_value_1,
        };
        let mut decoded_bytes_3 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 1],
            &mut decoded_bytes_3,
        );
        let decoded_value_4 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_3)?;
        let decoded_value_5 = NegativeTag {
            payload: decoded_value_4,
        };
        let mut decoded_bytes_6 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 2],
            &mut decoded_bytes_6,
        );
        let decoded_value_7 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_6)?;
        let decoded_value_8 = HugeTag {
            payload: decoded_value_7,
        };
        let decoded_value_9 = ParametricValuesResult {
            expr_box: decoded_value_2,
            negative: decoded_value_5,
            huge: decoded_value_8,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 3);
        Ok(decoded_value_9)
    }

    pub fn descriptor() -> xlsynth::AotEntrypointDescriptor<'static> {
        unsafe {
            xlsynth::AotEntrypointDescriptor::from_raw_parts_unchecked(
                ENTRYPOINTS_PROTO,
                __xlsynth_aot_linked_symbol_parametric_values as *const () as usize,
                xlsynth::AotEntrypointMetadata {
                    symbol: "__parametric_values__exercise_parametric_values".to_string(),
                    input_buffer_sizes: INPUT_BUFFER_SIZES.to_vec(),
                    input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS.to_vec(),
                    output_buffer_sizes: OUTPUT_BUFFER_SIZES.to_vec(),
                    output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS.to_vec(),
                    temp_buffer_size: 0,
                    temp_buffer_alignment: 1,
                },
            )
        }
    }

    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the ABI buffers owned by `xlsynth::AotRunner`; create
    /// one runner per concurrent caller instead of sharing it across
    /// threads.
    pub struct Runner {
        inner: xlsynth::AotRunner<'static>,
    }

    impl Runner {
        /// # Errors
        ///
        /// Returns an error if the descriptor metadata cannot initialize an AOT
        /// runner.
        pub fn new() -> Result<Self, xlsynth::XlsynthError> {
            Ok(Self {
                inner: xlsynth::AotRunner::new(descriptor())?,
            })
        }

        /// Runs the entrypoint and returns the output together with
        /// trace/assert events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            expr_box: &ExprBox8,
            negative: &NegativeTag,
            huge: &HugeTag,
        ) -> Result<xlsynth::AotRunResult<ParametricValuesResult>, xlsynth::XlsynthError> {
            encode_input_0(expr_box, self.inner.input_mut(0))?;
            encode_input_1(negative, self.inner.input_mut(1))?;
            encode_input_2(huge, self.inner.input_mut(2))?;
            let result = self
                .inner
                .run_with_events(|inner| decode_output_0(inner.output(0)))?;
            Ok(xlsynth::AotRunResult {
                output: result.output?,
                trace_messages: result.trace_messages,
                assert_messages: result.assert_messages,
            })
        }

        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run(
            &mut self,
            expr_box: &ExprBox8,
            negative: &NegativeTag,
            huge: &HugeTag,
        ) -> Result<ParametricValuesResult, xlsynth::XlsynthError> {
            encode_input_0(expr_box, self.inner.input_mut(0))?;
            encode_input_1(negative, self.inner.input_mut(1))?;
            encode_input_2(huge, self.inner.input_mut(2))?;
            self.inner.run()?;
            decode_output_0(self.inner.output(0))
        }
    }

    pub fn new_runner() -> Result<Runner, xlsynth::XlsynthError> {
        Runner::new()
    }
}
