// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "parametric_shapes".

pub mod parametric_shapes {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use xlsynth::{IrSBits, IrUBits, IrValue};

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Box__N_8 {
        pub value: IrUBits<8>,
    }

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Box__N_16 {
        pub value: IrUBits<16>,
    }

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Matrix__R_2__C_3 {
        pub rows: [[IrUBits<8>; 3]; 2],
    }

    pub type Box8 = Box__N_8;

    pub type Box16 = Box__N_16;

    pub type Matrix2x3 = Matrix__R_2__C_3;

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParametricShapesResult {
        pub box8: Box8,
        pub box16: Box16,
        pub matrix: Matrix2x3,
    }

    unsafe extern "C" {
        #[link_name = "__parametric_shapes__exercise_parametric_shapes"]
        fn __xlsynth_aot_linked_symbol_parametric_shapes();
    }

    const ENTRYPOINTS_PROTO: &[u8] = include_bytes!("parametric_shapes.entrypoints.pb");
    const INPUT_BUFFER_SIZES: &[usize] = &[1, 2, 6];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8, 8, 8];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[10];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];

    const INPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] =
        &[xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        }];
    const INPUT1_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] =
        &[xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 2,
            padded_size: 2,
        }];
    const INPUT2_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 5,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const OUTPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 2,
            padded_size: 2,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 5,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 6,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 7,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 8,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 9,
            data_size: 1,
            padded_size: 1,
        },
    ];

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(_value: &Box8, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).value).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT0_LAYOUT.len(), 1);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_1(_value: &Box16, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 2);
        dst.fill(0);
        let encoded_bytes = ((*_value).value).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT1_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT1_LAYOUT.len(), 1);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_2(_value: &Matrix2x3, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 6);
        dst.fill(0);
        for index_0 in 0..2 {
            for index_1 in 0..3 {
                let encoded_bytes = ((((*_value).rows)[index_0])[index_1]).to_le_bytes()?;
                xlsynth::aot_runner::write_leaf_element(
                    dst,
                    &INPUT2_LAYOUT[0usize + index_0 * 3 + index_1],
                    &encoded_bytes,
                );
            }
        }
        debug_assert_eq!(INPUT2_LAYOUT.len(), 6);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<ParametricShapesResult, xlsynth::XlsynthError> {
        debug_assert_eq!(src.len(), 10);
        let mut decoded_bytes_0 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(src, &OUTPUT0_LAYOUT[0usize], &mut decoded_bytes_0);
        let decoded_value_1 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_0)?;
        let decoded_value_2 = Box8 {
            value: decoded_value_1,
        };
        let mut decoded_bytes_3 = vec![0u8; 2];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 1],
            &mut decoded_bytes_3,
        );
        let decoded_value_4 = xlsynth::IrUBits::<16>::from_le_bytes(&decoded_bytes_3)?;
        let decoded_value_5 = Box16 {
            value: decoded_value_4,
        };
        let mut decoded_items_7 = Vec::with_capacity(2);
        for index_0 in 0..2 {
            let mut decoded_items_9 = Vec::with_capacity(3);
            for index_1 in 0..3 {
                let mut decoded_bytes_10 = vec![0u8; 1];
                xlsynth::aot_runner::read_leaf_element(
                    src,
                    &OUTPUT0_LAYOUT[0usize + 2 + index_0 * 3 + index_1],
                    &mut decoded_bytes_10,
                );
                let decoded_value_11 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_10)?;
                decoded_items_9.push(decoded_value_11);
            }
            let decoded_value_8: [IrUBits<8>; 3] =
                match std::convert::TryInto::try_into(decoded_items_9) {
                    Ok(value) => value,
                    Err(values) => {
                        return Err(xlsynth::XlsynthError(format!(
                            "AOT decode internal error: expected 3 array elements, got {}",
                            values.len()
                        )))
                    }
                };
            decoded_items_7.push(decoded_value_8);
        }
        let decoded_value_6: [[IrUBits<8>; 3]; 2] =
            match std::convert::TryInto::try_into(decoded_items_7) {
                Ok(value) => value,
                Err(values) => {
                    return Err(xlsynth::XlsynthError(format!(
                        "AOT decode internal error: expected 2 array elements, got {}",
                        values.len()
                    )))
                }
            };
        let decoded_value_12 = Matrix2x3 {
            rows: decoded_value_6,
        };
        let decoded_value_13 = ParametricShapesResult {
            box8: decoded_value_2,
            box16: decoded_value_5,
            matrix: decoded_value_12,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 8);
        Ok(decoded_value_13)
    }

    pub fn descriptor() -> xlsynth::AotEntrypointDescriptor<'static> {
        unsafe {
            xlsynth::AotEntrypointDescriptor::from_raw_parts_unchecked(
                ENTRYPOINTS_PROTO,
                __xlsynth_aot_linked_symbol_parametric_shapes as *const () as usize,
                xlsynth::AotEntrypointMetadata {
                    symbol: "__parametric_shapes__exercise_parametric_shapes".to_string(),
                    input_buffer_sizes: INPUT_BUFFER_SIZES.to_vec(),
                    input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS.to_vec(),
                    output_buffer_sizes: OUTPUT_BUFFER_SIZES.to_vec(),
                    output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS.to_vec(),
                    temp_buffer_size: 0,
                    temp_buffer_alignment: 1,
                },
            )
        }
    }

    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the ABI buffers owned by `xlsynth::AotRunner`; create
    /// one runner per concurrent caller instead of sharing it across
    /// threads.
    pub struct Runner {
        inner: xlsynth::AotRunner<'static>,
    }

    impl Runner {
        /// # Errors
        ///
        /// Returns an error if the descriptor metadata cannot initialize an AOT
        /// runner.
        pub fn new() -> Result<Self, xlsynth::XlsynthError> {
            Ok(Self {
                inner: xlsynth::AotRunner::new(descriptor())?,
            })
        }

        /// Runs the entrypoint and returns the output together with
        /// trace/assert events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            box8: &Box8,
            box16: &Box16,
            matrix: &Matrix2x3,
        ) -> Result<xlsynth::AotRunResult<ParametricShapesResult>, xlsynth::XlsynthError> {
            encode_input_0(box8, self.inner.input_mut(0))?;
            encode_input_1(box16, self.inner.input_mut(1))?;
            encode_input_2(matrix, self.inner.input_mut(2))?;
            let result = self
                .inner
                .run_with_events(|inner| decode_output_0(inner.output(0)))?;
            Ok(xlsynth::AotRunResult {
                output: result.output?,
                trace_messages: result.trace_messages,
                assert_messages: result.assert_messages,
            })
        }

        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run(
            &mut self,
            box8: &Box8,
            box16: &Box16,
            matrix: &Matrix2x3,
        ) -> Result<ParametricShapesResult, xlsynth::XlsynthError> {
            encode_input_0(box8, self.inner.input_mut(0))?;
            encode_input_1(box16, self.inner.input_mut(1))?;
            encode_input_2(matrix, self.inner.input_mut(2))?;
            self.inner.run()?;
            decode_output_0(self.inner.output(0))
        }
    }

    pub fn new_runner() -> Result<Runner, xlsynth::XlsynthError> {
        Runner::new()
    }
}
