// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "parametric_arrays".

pub mod parametric_arrays {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use xlsynth::{IrSBits, IrUBits, IrValue};

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ArrayBox__N_4 {
        pub items: [IrUBits<8>; 4],
    }

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Box__N_8 {
        pub value: IrUBits<8>,
    }

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Box__N_16 {
        pub value: IrUBits<16>,
    }

    pub type ArrayBox4 = ArrayBox__N_4;

    pub type Box8Array4 = [Box__N_8; 4];

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct OuterBox {
        pub inner: Box__N_8,
        pub wider: Box__N_16,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParametricArraysResult {
        pub array_box: ArrayBox4,
        pub box_array: Box8Array4,
        pub outer: OuterBox,
    }

    unsafe extern "C" {
        #[link_name = "__parametric_arrays__exercise_parametric_arrays"]
        fn __xlsynth_aot_linked_symbol_parametric_arrays();
    }

    const ENTRYPOINTS_PROTO: &[u8] = include_bytes!("parametric_arrays.entrypoints.pb");
    const INPUT_BUFFER_SIZES: &[usize] = &[4, 4, 4];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8, 8, 8];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[12];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];

    const INPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const INPUT1_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const INPUT2_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 2,
            padded_size: 2,
        },
    ];
    const OUTPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 5,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 6,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 7,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 8,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 10,
            data_size: 2,
            padded_size: 2,
        },
    ];

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(_value: &ArrayBox4, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 4);
        dst.fill(0);
        for index_0 in 0..4 {
            let encoded_bytes = (((*_value).items)[index_0]).to_le_bytes()?;
            xlsynth::aot_runner::write_leaf_element(
                dst,
                &INPUT0_LAYOUT[0usize + index_0],
                &encoded_bytes,
            );
        }
        debug_assert_eq!(INPUT0_LAYOUT.len(), 4);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_1(_value: &Box8Array4, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 4);
        dst.fill(0);
        for index_0 in 0..4 {
            let encoded_bytes = (((*_value)[index_0]).value).to_le_bytes()?;
            xlsynth::aot_runner::write_leaf_element(
                dst,
                &INPUT1_LAYOUT[0usize + index_0],
                &encoded_bytes,
            );
        }
        debug_assert_eq!(INPUT1_LAYOUT.len(), 4);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_2(_value: &OuterBox, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 4);
        dst.fill(0);
        let encoded_bytes = (((*_value).inner).value).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT2_LAYOUT[0usize], &encoded_bytes);
        let encoded_bytes = (((*_value).wider).value).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT2_LAYOUT[0usize + 1], &encoded_bytes);
        debug_assert_eq!(INPUT2_LAYOUT.len(), 2);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<ParametricArraysResult, xlsynth::XlsynthError> {
        debug_assert_eq!(src.len(), 12);
        let mut decoded_items_1 = Vec::with_capacity(4);
        for index_0 in 0..4 {
            let mut decoded_bytes_2 = vec![0u8; 1];
            xlsynth::aot_runner::read_leaf_element(
                src,
                &OUTPUT0_LAYOUT[0usize + index_0],
                &mut decoded_bytes_2,
            );
            let decoded_value_3 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_2)?;
            decoded_items_1.push(decoded_value_3);
        }
        let decoded_value_0: [IrUBits<8>; 4] =
            match std::convert::TryInto::try_into(decoded_items_1) {
                Ok(value) => value,
                Err(values) => {
                    return Err(xlsynth::XlsynthError(format!(
                        "AOT decode internal error: expected 4 array elements, got {}",
                        values.len()
                    )))
                }
            };
        let decoded_value_4 = ArrayBox4 {
            items: decoded_value_0,
        };
        let mut decoded_items_6 = Vec::with_capacity(4);
        for index_1 in 0..4 {
            let mut decoded_bytes_7 = vec![0u8; 1];
            xlsynth::aot_runner::read_leaf_element(
                src,
                &OUTPUT0_LAYOUT[0usize + 4 + index_1],
                &mut decoded_bytes_7,
            );
            let decoded_value_8 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_7)?;
            let decoded_value_9 = Box__N_8 {
                value: decoded_value_8,
            };
            decoded_items_6.push(decoded_value_9);
        }
        let decoded_value_5: Box8Array4 = match std::convert::TryInto::try_into(decoded_items_6) {
            Ok(value) => value,
            Err(values) => {
                return Err(xlsynth::XlsynthError(format!(
                    "AOT decode internal error: expected 4 array elements, got {}",
                    values.len()
                )))
            }
        };
        let mut decoded_bytes_10 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 8],
            &mut decoded_bytes_10,
        );
        let decoded_value_11 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_10)?;
        let decoded_value_12 = Box__N_8 {
            value: decoded_value_11,
        };
        let mut decoded_bytes_13 = vec![0u8; 2];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 8 + 1],
            &mut decoded_bytes_13,
        );
        let decoded_value_14 = xlsynth::IrUBits::<16>::from_le_bytes(&decoded_bytes_13)?;
        let decoded_value_15 = Box__N_16 {
            value: decoded_value_14,
        };
        let decoded_value_16 = OuterBox {
            inner: decoded_value_12,
            wider: decoded_value_15,
        };
        let decoded_value_17 = ParametricArraysResult {
            array_box: decoded_value_4,
            box_array: decoded_value_5,
            outer: decoded_value_16,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 10);
        Ok(decoded_value_17)
    }

    pub fn descriptor() -> xlsynth::AotEntrypointDescriptor<'static> {
        unsafe {
            xlsynth::AotEntrypointDescriptor::from_raw_parts_unchecked(
                ENTRYPOINTS_PROTO,
                __xlsynth_aot_linked_symbol_parametric_arrays as *const () as usize,
                xlsynth::AotEntrypointMetadata {
                    symbol: "__parametric_arrays__exercise_parametric_arrays".to_string(),
                    input_buffer_sizes: INPUT_BUFFER_SIZES.to_vec(),
                    input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS.to_vec(),
                    output_buffer_sizes: OUTPUT_BUFFER_SIZES.to_vec(),
                    output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS.to_vec(),
                    temp_buffer_size: 0,
                    temp_buffer_alignment: 1,
                },
            )
        }
    }

    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the ABI buffers owned by `xlsynth::AotRunner`; create
    /// one runner per concurrent caller instead of sharing it across
    /// threads.
    pub struct Runner {
        inner: xlsynth::AotRunner<'static>,
    }

    impl Runner {
        /// # Errors
        ///
        /// Returns an error if the descriptor metadata cannot initialize an AOT
        /// runner.
        pub fn new() -> Result<Self, xlsynth::XlsynthError> {
            Ok(Self {
                inner: xlsynth::AotRunner::new(descriptor())?,
            })
        }

        /// Runs the entrypoint and returns the output together with
        /// trace/assert events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            array_box: &ArrayBox4,
            box_array: &Box8Array4,
            outer: &OuterBox,
        ) -> Result<xlsynth::AotRunResult<ParametricArraysResult>, xlsynth::XlsynthError> {
            encode_input_0(array_box, self.inner.input_mut(0))?;
            encode_input_1(box_array, self.inner.input_mut(1))?;
            encode_input_2(outer, self.inner.input_mut(2))?;
            let result = self
                .inner
                .run_with_events(|inner| decode_output_0(inner.output(0)))?;
            Ok(xlsynth::AotRunResult {
                output: result.output?,
                trace_messages: result.trace_messages,
                assert_messages: result.assert_messages,
            })
        }

        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run(
            &mut self,
            array_box: &ArrayBox4,
            box_array: &Box8Array4,
            outer: &OuterBox,
        ) -> Result<ParametricArraysResult, xlsynth::XlsynthError> {
            encode_input_0(array_box, self.inner.input_mut(0))?;
            encode_input_1(box_array, self.inner.input_mut(1))?;
            encode_input_2(outer, self.inner.input_mut(2))?;
            self.inner.run()?;
            decode_output_0(self.inner.output(0))
        }
    }

    pub fn new_runner() -> Result<Runner, xlsynth::XlsynthError> {
        Runner::new()
    }
}
