// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "parametric_box".

pub mod parametric_box {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use xlsynth::{IrSBits, IrUBits, IrValue};

    #[allow(non_camel_case_types)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Box__N_8 {
        pub value: IrUBits<8>,
    }

    pub type Box8 = Box__N_8;

    unsafe extern "C" {
        #[link_name = "__parametric_box__echo_box"]
        fn __xlsynth_aot_linked_symbol_parametric_box();
    }

    const ENTRYPOINTS_PROTO: &[u8] = include_bytes!("parametric_box.entrypoints.pb");
    const INPUT_BUFFER_SIZES: &[usize] = &[1];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[1];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];

    const INPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] =
        &[xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        }];
    const OUTPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] =
        &[xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        }];

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(_value: &Box8, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 1);
        dst.fill(0);
        let encoded_bytes = ((*_value).value).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize], &encoded_bytes);
        debug_assert_eq!(INPUT0_LAYOUT.len(), 1);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<Box8, xlsynth::XlsynthError> {
        debug_assert_eq!(src.len(), 1);
        let mut decoded_bytes_0 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(src, &OUTPUT0_LAYOUT[0usize], &mut decoded_bytes_0);
        let decoded_value_1 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_0)?;
        let decoded_value_2 = Box8 {
            value: decoded_value_1,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 1);
        Ok(decoded_value_2)
    }

    pub fn descriptor() -> xlsynth::AotEntrypointDescriptor<'static> {
        unsafe {
            xlsynth::AotEntrypointDescriptor::from_raw_parts_unchecked(
                ENTRYPOINTS_PROTO,
                __xlsynth_aot_linked_symbol_parametric_box as *const () as usize,
                xlsynth::AotEntrypointMetadata {
                    symbol: "__parametric_box__echo_box".to_string(),
                    input_buffer_sizes: INPUT_BUFFER_SIZES.to_vec(),
                    input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS.to_vec(),
                    output_buffer_sizes: OUTPUT_BUFFER_SIZES.to_vec(),
                    output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS.to_vec(),
                    temp_buffer_size: 0,
                    temp_buffer_alignment: 1,
                },
            )
        }
    }

    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the ABI buffers owned by `xlsynth::AotRunner`; create
    /// one runner per concurrent caller instead of sharing it across
    /// threads.
    pub struct Runner {
        inner: xlsynth::AotRunner<'static>,
    }

    impl Runner {
        /// # Errors
        ///
        /// Returns an error if the descriptor metadata cannot initialize an AOT
        /// runner.
        pub fn new() -> Result<Self, xlsynth::XlsynthError> {
            Ok(Self {
                inner: xlsynth::AotRunner::new(descriptor())?,
            })
        }

        /// Runs the entrypoint and returns the output together with
        /// trace/assert events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            x: &Box8,
        ) -> Result<xlsynth::AotRunResult<Box8>, xlsynth::XlsynthError> {
            encode_input_0(x, self.inner.input_mut(0))?;
            let result = self
                .inner
                .run_with_events(|inner| decode_output_0(inner.output(0)))?;
            Ok(xlsynth::AotRunResult {
                output: result.output?,
                trace_messages: result.trace_messages,
                assert_messages: result.assert_messages,
            })
        }

        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run(&mut self, x: &Box8) -> Result<Box8, xlsynth::XlsynthError> {
            encode_input_0(x, self.inner.input_mut(0))?;
            self.inner.run()?;
            decode_output_0(self.inner.output(0))
        }
    }

    pub fn new_runner() -> Result<Runner, xlsynth::XlsynthError> {
        Runner::new()
    }
}
