// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "widget_frob".

pub mod widget_types {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use xlsynth::{IrSBits, IrUBits, IrValue};

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum WidgetMode {
        Idle = 0,
        Frob = 1,
        Quux = 2,
    }

    impl From<WidgetMode> for IrValue {
        fn from(value: WidgetMode) -> Self {
            match value {
                WidgetMode::Idle => IrValue::make_ubits(2, 0).unwrap(),
                WidgetMode::Frob => IrValue::make_ubits(2, 1).unwrap(),
                WidgetMode::Quux => IrValue::make_ubits(2, 2).unwrap(),
            }
        }
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum SignedWidgetMode {
        Negative = -1,
        Neutral = 0,
        Positive = 1,
    }

    impl From<SignedWidgetMode> for IrValue {
        fn from(value: SignedWidgetMode) -> Self {
            match value {
                SignedWidgetMode::Negative => IrValue::make_sbits(2, -1).unwrap(),
                SignedWidgetMode::Neutral => IrValue::make_sbits(2, 0).unwrap(),
                SignedWidgetMode::Positive => IrValue::make_sbits(2, 1).unwrap(),
            }
        }
    }

    pub type FrobNibbles = [IrUBits<4>; 3];

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct WidgetTuning {
        pub frob_bias: IrUBits<4>,
        pub wobble_trim: IrSBits<4>,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Widget {
        pub widget_id: IrUBits<8>,
        pub mode: WidgetMode,
        pub frobs: FrobNibbles,
        pub tuning: WidgetTuning,
        pub wobble: IrSBits<4>,
        pub signed_mode: SignedWidgetMode,
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct WidgetOutcome {
        pub next_widget_id: IrUBits<8>,
        pub selected_frob: IrUBits<4>,
        pub mode: WidgetMode,
        pub adjusted_wobble: IrSBits<4>,
        pub signed_mode: SignedWidgetMode,
    }

    unsafe extern "C" {
        #[link_name = "__widget_types__frob_widget"]
        fn __xlsynth_aot_linked_symbol_widget_frob();
    }

    const ENTRYPOINTS_PROTO: &[u8] = include_bytes!("widget_frob.entrypoints.pb");
    const INPUT_BUFFER_SIZES: &[usize] = &[9, 3];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8, 1];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[5];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];

    const INPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 5,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 6,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 7,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 8,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const INPUT1_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const OUTPUT0_LAYOUT: &[xlsynth::aot_entrypoint_metadata::AotElementLayout] = &[
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
        xlsynth::aot_entrypoint_metadata::AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
    ];

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(_value: &Widget, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 9);
        dst.fill(0);
        let encoded_bytes = ((*_value).widget_id).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize], &encoded_bytes);
        let encoded_value: u64 = match (*_value).mode {
            WidgetMode::Idle => 0,
            WidgetMode::Frob => 1,
            WidgetMode::Quux => 2,
        };
        let encoded_bits = xlsynth::IrUBits::<2>::from_u64(encoded_value)?;
        let encoded_bytes = encoded_bits.to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 1], &encoded_bytes);
        for index_0 in 0..3 {
            let encoded_bytes = (((*_value).frobs)[index_0]).to_le_bytes()?;
            xlsynth::aot_runner::write_leaf_element(
                dst,
                &INPUT0_LAYOUT[0usize + 2 + index_0],
                &encoded_bytes,
            );
        }
        let encoded_bytes = (((*_value).tuning).frob_bias).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 5], &encoded_bytes);
        let encoded_bytes = (((*_value).tuning).wobble_trim).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(
            dst,
            &INPUT0_LAYOUT[0usize + 5 + 1],
            &encoded_bytes,
        );
        let encoded_bytes = ((*_value).wobble).to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 7], &encoded_bytes);
        let encoded_value: i64 = match (*_value).signed_mode {
            SignedWidgetMode::Negative => -1,
            SignedWidgetMode::Neutral => 0,
            SignedWidgetMode::Positive => 1,
        };
        let encoded_bits = xlsynth::IrSBits::<2>::from_i64(encoded_value)?;
        let encoded_bytes = encoded_bits.to_le_bytes()?;
        xlsynth::aot_runner::write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 8], &encoded_bytes);
        debug_assert_eq!(INPUT0_LAYOUT.len(), 9);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_1(_value: &FrobNibbles, dst: &mut [u8]) -> Result<(), xlsynth::XlsynthError> {
        debug_assert_eq!(dst.len(), 3);
        dst.fill(0);
        for index_0 in 0..3 {
            let encoded_bytes = ((*_value)[index_0]).to_le_bytes()?;
            xlsynth::aot_runner::write_leaf_element(
                dst,
                &INPUT1_LAYOUT[0usize + index_0],
                &encoded_bytes,
            );
        }
        debug_assert_eq!(INPUT1_LAYOUT.len(), 3);
        Ok(())
    }

    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<WidgetOutcome, xlsynth::XlsynthError> {
        debug_assert_eq!(src.len(), 5);
        let mut decoded_bytes_0 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(src, &OUTPUT0_LAYOUT[0usize], &mut decoded_bytes_0);
        let decoded_value_1 = xlsynth::IrUBits::<8>::from_le_bytes(&decoded_bytes_0)?;
        let mut decoded_bytes_2 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 1],
            &mut decoded_bytes_2,
        );
        let decoded_value_3 = xlsynth::IrUBits::<4>::from_le_bytes(&decoded_bytes_2)?;
        let mut decoded_bytes_4 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 2],
            &mut decoded_bytes_4,
        );
        let decoded_bits_5 = xlsynth::IrUBits::<2>::from_le_bytes(&decoded_bytes_4)?;
        let decoded_scalar_6 = decoded_bits_5.to_u64()?;
        let decoded_value_7 = match decoded_scalar_6 {
            0 => WidgetMode::Idle,
            1 => WidgetMode::Frob,
            2 => WidgetMode::Quux,
            value => {
                return Err(xlsynth::XlsynthError(format!(
                    "AOT decode invalid enum value {value} for WidgetMode"
                )))
            }
        };
        let mut decoded_bytes_8 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 3],
            &mut decoded_bytes_8,
        );
        let decoded_value_9 = xlsynth::IrSBits::<4>::from_le_bytes(&decoded_bytes_8)?;
        let mut decoded_bytes_10 = vec![0u8; 1];
        xlsynth::aot_runner::read_leaf_element(
            src,
            &OUTPUT0_LAYOUT[0usize + 4],
            &mut decoded_bytes_10,
        );
        let decoded_bits_11 = xlsynth::IrSBits::<2>::from_le_bytes(&decoded_bytes_10)?;
        let decoded_scalar_12 = decoded_bits_11.to_i64()?;
        let decoded_value_13 = match decoded_scalar_12 {
            -1 => SignedWidgetMode::Negative,
            0 => SignedWidgetMode::Neutral,
            1 => SignedWidgetMode::Positive,
            value => {
                return Err(xlsynth::XlsynthError(format!(
                    "AOT decode invalid enum value {value} for SignedWidgetMode"
                )))
            }
        };
        let decoded_value_14 = WidgetOutcome {
            next_widget_id: decoded_value_1,
            selected_frob: decoded_value_3,
            mode: decoded_value_7,
            adjusted_wobble: decoded_value_9,
            signed_mode: decoded_value_13,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 5);
        Ok(decoded_value_14)
    }

    pub fn descriptor() -> xlsynth::AotEntrypointDescriptor<'static> {
        unsafe {
            xlsynth::AotEntrypointDescriptor::from_raw_parts_unchecked(
                ENTRYPOINTS_PROTO,
                __xlsynth_aot_linked_symbol_widget_frob as *const () as usize,
                xlsynth::AotEntrypointMetadata {
                    symbol: "__widget_types__frob_widget".to_string(),
                    input_buffer_sizes: INPUT_BUFFER_SIZES.to_vec(),
                    input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS.to_vec(),
                    output_buffer_sizes: OUTPUT_BUFFER_SIZES.to_vec(),
                    output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS.to_vec(),
                    temp_buffer_size: 0,
                    temp_buffer_alignment: 1,
                },
            )
        }
    }

    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the ABI buffers owned by `xlsynth::AotRunner`; create
    /// one runner per concurrent caller instead of sharing it across
    /// threads.
    pub struct Runner {
        inner: xlsynth::AotRunner<'static>,
    }

    impl Runner {
        /// # Errors
        ///
        /// Returns an error if the descriptor metadata cannot initialize an AOT
        /// runner.
        pub fn new() -> Result<Self, xlsynth::XlsynthError> {
            Ok(Self {
                inner: xlsynth::AotRunner::new(descriptor())?,
            })
        }

        /// Runs the entrypoint and returns the output together with
        /// trace/assert events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            widget: &Widget,
            garnish: &FrobNibbles,
        ) -> Result<xlsynth::AotRunResult<WidgetOutcome>, xlsynth::XlsynthError> {
            encode_input_0(widget, self.inner.input_mut(0))?;
            encode_input_1(garnish, self.inner.input_mut(1))?;
            let result = self
                .inner
                .run_with_events(|inner| decode_output_0(inner.output(0)))?;
            Ok(xlsynth::AotRunResult {
                output: result.output?,
                trace_messages: result.trace_messages,
                assert_messages: result.assert_messages,
            })
        }

        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run(
            &mut self,
            widget: &Widget,
            garnish: &FrobNibbles,
        ) -> Result<WidgetOutcome, xlsynth::XlsynthError> {
            encode_input_0(widget, self.inner.input_mut(0))?;
            encode_input_1(garnish, self.inner.input_mut(1))?;
            self.inner.run()?;
            decode_output_0(self.inner.output(0))
        }
    }

    pub fn new_runner() -> Result<Runner, xlsynth::XlsynthError> {
        Runner::new()
    }
}
