// SPDX-License-Identifier: Apache-2.0
// Generated by xlsynth::aot_builder from DSLX build spec "widget_frob".

pub use xlsynth_aot_runtime::{AotArtifactMetadata, AotError, AotRunResult, SBits, UBits};
#[allow(unused_imports)]
use xlsynth_aot_runtime::{
    read_leaf_element, write_leaf_element, AotElementLayout, AotRunnerLayout,
    StandaloneRunner,
};
pub mod widget_types {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    use super::{
        read_leaf_element, write_leaf_element, AotArtifactMetadata, AotElementLayout,
        AotError, AotRunResult, AotRunnerLayout, SBits, StandaloneRunner, UBits,
    };
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum WidgetMode {
        Idle = 0,
        Frob = 1,
        Quux = 2,
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum SignedWidgetMode {
        Negative = -1,
        Neutral = 0,
        Positive = 1,
    }
    pub type FrobNibbles = [UBits<4>; 3];
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct WidgetTuning {
        pub frob_bias: UBits<4>,
        pub wobble_trim: SBits<4>,
    }
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Widget {
        pub widget_id: UBits<8>,
        pub mode: WidgetMode,
        pub frobs: FrobNibbles,
        pub tuning: WidgetTuning,
        pub wobble: SBits<4>,
        pub signed_mode: SignedWidgetMode,
    }
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct WidgetOutcome {
        pub next_widget_id: UBits<8>,
        pub selected_frob: UBits<4>,
        pub mode: WidgetMode,
        pub adjusted_wobble: SBits<4>,
        pub signed_mode: SignedWidgetMode,
    }
    unsafe extern "C" {
        #[link_name = "__xlsynth_standalone_widget_frob"]
        fn __xlsynth_aot_linked_symbol_widget_frob();
    }
    const INPUT_BUFFER_SIZES: &[usize] = &[9, 3];
    const INPUT_BUFFER_ALIGNMENTS: &[usize] = &[8, 1];
    const OUTPUT_BUFFER_SIZES: &[usize] = &[5];
    const OUTPUT_BUFFER_ALIGNMENTS: &[usize] = &[8];
    const RUNNER_LAYOUT: AotRunnerLayout = AotRunnerLayout {
        input_buffer_sizes: INPUT_BUFFER_SIZES,
        input_buffer_alignments: INPUT_BUFFER_ALIGNMENTS,
        output_buffer_sizes: OUTPUT_BUFFER_SIZES,
        output_buffer_alignments: OUTPUT_BUFFER_ALIGNMENTS,
        temp_buffer_size: 0,
        temp_buffer_alignment: 1,
    };
    /// Runtime-visible metadata for the generated standalone artifact.
    pub const ARTIFACT_METADATA: AotArtifactMetadata = AotArtifactMetadata {
        abi_version: 1,
        entrypoint_symbol: "__xlsynth_standalone_widget_frob",
        has_asserts: false,
        has_traces: false,
    };
    const INPUT0_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 5,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 6,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 7,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 8,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const INPUT1_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
    ];
    const OUTPUT0_LAYOUT: &[AotElementLayout] = &[
        AotElementLayout {
            offset: 0,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 1,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 2,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 3,
            data_size: 1,
            padded_size: 1,
        },
        AotElementLayout {
            offset: 4,
            data_size: 1,
            padded_size: 1,
        },
    ];
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_0(_value: &Widget, dst: &mut [u8]) -> Result<(), AotError> {
        debug_assert_eq!(dst.len(), 9);
        dst.fill(0);
        let encoded_bytes = ((*_value).widget_id).to_le_bytes()?;
        write_leaf_element(dst, &INPUT0_LAYOUT[0usize], &encoded_bytes);
        let encoded_value: u64 = match (*_value).mode {
            WidgetMode::Idle => 0,
            WidgetMode::Frob => 1,
            WidgetMode::Quux => 2,
        };
        let encoded_bits = UBits::<2>::from_u64(encoded_value)?;
        let encoded_bytes = encoded_bits.to_le_bytes()?;
        write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 1], &encoded_bytes);
        for index_0 in 0..3 {
            let encoded_bytes = (((*_value).frobs)[index_0]).to_le_bytes()?;
            write_leaf_element(
                dst,
                &INPUT0_LAYOUT[0usize + 2 + index_0],
                &encoded_bytes,
            );
        }
        let encoded_bytes = (((*_value).tuning).frob_bias).to_le_bytes()?;
        write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 5], &encoded_bytes);
        let encoded_bytes = (((*_value).tuning).wobble_trim).to_le_bytes()?;
        write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 5 + 1], &encoded_bytes);
        let encoded_bytes = ((*_value).wobble).to_le_bytes()?;
        write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 7], &encoded_bytes);
        let encoded_value: i64 = match (*_value).signed_mode {
            SignedWidgetMode::Negative => -1,
            SignedWidgetMode::Neutral => 0,
            SignedWidgetMode::Positive => 1,
        };
        let encoded_bits = SBits::<2>::from_i64(encoded_value)?;
        let encoded_bytes = encoded_bits.to_le_bytes()?;
        write_leaf_element(dst, &INPUT0_LAYOUT[0usize + 8], &encoded_bytes);
        debug_assert_eq!(INPUT0_LAYOUT.len(), 9);
        Ok(())
    }
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn encode_input_1(_value: &FrobNibbles, dst: &mut [u8]) -> Result<(), AotError> {
        debug_assert_eq!(dst.len(), 3);
        dst.fill(0);
        for index_0 in 0..3 {
            let encoded_bytes = ((*_value)[index_0]).to_le_bytes()?;
            write_leaf_element(dst, &INPUT1_LAYOUT[0usize + index_0], &encoded_bytes);
        }
        debug_assert_eq!(INPUT1_LAYOUT.len(), 3);
        Ok(())
    }
    #[allow(clippy::deref_addrof, clippy::explicit_auto_deref, clippy::identity_op)]
    fn decode_output_0(src: &[u8]) -> Result<WidgetOutcome, AotError> {
        debug_assert_eq!(src.len(), 5);
        let mut decoded_bytes_0 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize], &mut decoded_bytes_0);
        let decoded_value_1 = UBits::<8>::from_le_bytes(&decoded_bytes_0)?;
        let mut decoded_bytes_2 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize + 1], &mut decoded_bytes_2);
        let decoded_value_3 = UBits::<4>::from_le_bytes(&decoded_bytes_2)?;
        let mut decoded_bytes_4 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize + 2], &mut decoded_bytes_4);
        let decoded_bits_5 = UBits::<2>::from_le_bytes(&decoded_bytes_4)?;
        let decoded_scalar_6 = decoded_bits_5.to_u64()?;
        let decoded_value_7 = match decoded_scalar_6 {
            0 => WidgetMode::Idle,
            1 => WidgetMode::Frob,
            2 => WidgetMode::Quux,
            value => {
                return Err(
                    AotError(
                        format!("AOT decode invalid enum value {value} for WidgetMode"),
                    ),
                );
            }
        };
        let mut decoded_bytes_8 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize + 3], &mut decoded_bytes_8);
        let decoded_value_9 = SBits::<4>::from_le_bytes(&decoded_bytes_8)?;
        let mut decoded_bytes_10 = vec![0u8; 1];
        read_leaf_element(src, &OUTPUT0_LAYOUT[0usize + 4], &mut decoded_bytes_10);
        let decoded_bits_11 = SBits::<2>::from_le_bytes(&decoded_bytes_10)?;
        let decoded_scalar_12 = decoded_bits_11.to_i64()?;
        let decoded_value_13 = match decoded_scalar_12 {
            -1 => SignedWidgetMode::Negative,
            0 => SignedWidgetMode::Neutral,
            1 => SignedWidgetMode::Positive,
            value => {
                return Err(
                    AotError(
                        format!(
                            "AOT decode invalid enum value {value} for SignedWidgetMode"
                        ),
                    ),
                );
            }
        };
        let decoded_value_14 = WidgetOutcome {
            next_widget_id: decoded_value_1,
            selected_frob: decoded_value_3,
            mode: decoded_value_7,
            adjusted_wobble: decoded_value_9,
            signed_mode: decoded_value_13,
        };
        debug_assert_eq!(OUTPUT0_LAYOUT.len(), 5);
        Ok(decoded_value_14)
    }
    /// Reusable runner for the generated typed DSLX AOT entrypoint.
    ///
    /// A runner caches the standalone ABI buffers; create one runner per
    /// concurrent caller instead of sharing it across threads.
    pub struct Runner {
        inner: StandaloneRunner,
    }
    impl Runner {
        /// Creates a reusable runner for the generated typed DSLX entrypoint.
        ///
        /// # Errors
        ///
        /// Returns an error if the standalone artifact metadata cannot initialize
        /// an AOT runner.
        pub fn new() -> Result<Self, AotError> {
            Ok(Self {
                inner: unsafe {
                    StandaloneRunner::new(
                        &ARTIFACT_METADATA,
                        __xlsynth_aot_linked_symbol_widget_frob as *const (),
                        &RUNNER_LAYOUT,
                    )?
                },
            })
        }
        /// Runs the entrypoint and returns the output together with assertion
        /// events.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, or output decoding
        /// fails.
        pub fn run_with_events(
            &mut self,
            widget: &Widget,
            garnish: &FrobNibbles,
        ) -> Result<AotRunResult<WidgetOutcome>, AotError> {
            encode_input_0(widget, self.inner.input_mut(0))?;
            encode_input_1(garnish, self.inner.input_mut(1))?;
            self.inner.run_raw();
            Ok(AotRunResult {
                output: decode_output_0(self.inner.output(0))?,
                assert_messages: self.inner.assert_messages().to_vec(),
            })
        }
        /// Runs the entrypoint and returns only the decoded output value.
        ///
        /// # Errors
        ///
        /// Returns an error if input packing, AOT execution, output decoding, or
        /// an XLS assertion fails.
        pub fn run(
            &mut self,
            widget: &Widget,
            garnish: &FrobNibbles,
        ) -> Result<WidgetOutcome, AotError> {
            encode_input_0(widget, self.inner.input_mut(0))?;
            encode_input_1(garnish, self.inner.input_mut(1))?;
            self.inner.run_raw();
            if let Some(first_assertion) = self.inner.assert_messages().first() {
                return Err(AotError(format!("XLS assertion failed: {first_assertion}")));
            }
            decode_output_0(self.inner.output(0))
        }
    }
    /// Creates a reusable runner for the generated typed DSLX entrypoint.
    pub fn new_runner() -> Result<Runner, AotError> {
        Runner::new()
    }
}
