work_dir = "/home/cdleary/proj/xlsynth-crate/xlsynth-g8r/fuzz"
target = "fuzz_aug_opt_equiv"
workers = "auto"
use_value_profile = true
timeout_seconds = 5
artifact_prefix = "artifacts/${target}"
corpus_dir = "corpus/${target}"
seeds_dirs = []
enable_unique_stderr_counter = true
hide_worker_output = true
ignore_crashes = true
ignore_timeouts = true
ignore_ooms = false
fork = 0
quarantine_crashing_corpus_inputs = true
seed_strip_line_regex = "^//.*"
seed_include_globs = []
seed_clean_existing = false
dictionary_path = ""
state_dir = "/tmp/fuzzmgr-state-fuzz_aug_opt_equiv"
cargo_home_dir = "/tmp/fuzzmgr-cargo-home-fuzz_aug_opt_equiv"
