[package]
name = "xlsynth-g8r"
version = "0.0.108"
edition = "2021"
authors = ["Christopher D. Leary <cdleary@gmail.com>"]
description = "XLS IR to gate mapping"
license = "Apache-2.0"
repository = "https://github.com/xlsynth/xlsynth-crate"
documentation = "https://docs.rs/xlsynth"
homepage = "https://github.com/xlsynth/xlsynth-crate"

[dependencies]
xlsynth = { path = "../xlsynth", version = "0.0.108" }
env_logger = "0.11"
log = "0.4"
clap = { version = "4.5.21", features = ["derive"] }
tempfile = "3.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = { version = "1.1", features = ["zlib-rs"], default-features = false }

[dev-dependencies]
test-case = "3.3.1"
arbitrary = { version = "1.3", features = ["derive"] }
libfuzzer-sys = "0.4"
pretty_assertions = "1.4.1"
regex = "1.5"
cargo_metadata = "0.19.2"

[lib]
name = "xlsynth_g8r"
path = "src/lib.rs"

[[bin]]
name = "g8r"
path = "src/main.rs"

[[bin]]
name = "try-parse-liberty"
path = "src/liberty/try_parse.rs"