# SPDX-License-Identifier: Apache-2.0

"""Combine the existing cargo-fuzz manifests for one smoke-suite build.

The generated package references the original target sources and support
libraries. Individual fuzz packages remain usable independently. Requires
Python 3.11+, like run_all_fuzz_tests.py.
"""

from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tomllib
from typing import Any

GENERATED_HEADER = "# Generated by scripts/fuzz_smoke_workspace.py; do not edit."


@dataclass(frozen=True)
class FuzzTarget:
    name: str
    fuzz_dir: Path
    required_features: tuple[str, ...]


@dataclass
class SmokeWorkspace:
    path: Path
    targets: list[FuzzTarget]
    features: dict[str, list[str]]

    def enabled_features(self, requested: list[str], defaults: bool) -> set[str]:
        """Expand package features, excluding dependency-feature selectors."""
        unknown = set(requested) - self.features.keys()
        if unknown:
            raise ValueError(f"unknown fuzz features: {', '.join(sorted(unknown))}")
        pending = [*requested, *(["default"] if defaults else [])]
        enabled: set[str] = set()
        while pending:
            feature = pending.pop()
            if feature in enabled:
                continue
            enabled.add(feature)
            pending.extend(
                value
                for value in self.features.get(feature, [])
                if value in self.features
            )
        return enabled


def toml_value(value: Any) -> str:
    """Encode the small set of TOML values used by dependency/bin declarations."""
    if isinstance(value, dict):
        return (
            "{ "
            + ", ".join(
                f"{json.dumps(key)} = {toml_value(item)}"
                for key, item in sorted(value.items())
            )
            + " }"
        )
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    if isinstance(value, (str, bool, int)):
        return json.dumps(value, ensure_ascii=False)
    raise ValueError(f"unsupported generated TOML value: {value!r}")


def merge_dependency(
    dependencies: dict[str, dict[str, Any]],
    name: str,
    declaration: str | dict[str, Any],
    fuzz_dir: Path,
) -> None:
    """Union features and intersect version requirements for one dependency."""
    incoming = (
        {"version": declaration} if isinstance(declaration, str) else dict(declaration)
    )
    supported = {"version", "path", "package", "features", "default-features"}
    unsupported = incoming.keys() - supported
    if unsupported:
        raise ValueError(
            f"{fuzz_dir}: dependency {name!r} uses unsupported smoke manifest "
            f"keys {sorted(unsupported)}; extend the merger before using them"
        )
    if "path" in incoming:
        incoming["path"] = str((fuzz_dir / incoming["path"]).resolve())
    if incoming.get("package") == name:
        del incoming["package"]
    current = dependencies.get(name)
    if current is None:
        dependencies[name] = incoming
        return
    for key in ("path", "package"):
        if current.get(key) != incoming.get(key):
            raise ValueError(
                f"{fuzz_dir}: conflicting {key} for dependency {name!r}: "
                f"{current.get(key)!r} versus {incoming.get(key)!r}"
            )
    # Comma-separated Cargo requirements are an intersection. Do not silently
    # choose one package's minimum version over another's stricter requirement.
    requirements = {
        part.strip()
        for spec in (current, incoming)
        for part in spec.get("version", "").split(",")
        if part.strip()
    }
    if requirements:
        current["version"] = ", ".join(sorted(requirements))
    current["features"] = sorted(
        set(current.get("features", [])) | set(incoming.get("features", []))
    )
    current["default-features"] = current.get("default-features", True) or incoming.get(
        "default-features", True
    )


def prepare_smoke_workspace(fuzz_dirs: list[Path], output: Path) -> SmokeWorkspace:
    """Generate one package from registered bins, dependencies and features."""
    manifest_path = output / "Cargo.toml"
    if manifest_path.exists():
        if not manifest_path.read_text(encoding="utf-8").startswith(GENERATED_HEADER):
            raise ValueError(
                f"refusing to overwrite non-generated manifest {manifest_path}"
            )
    elif output.exists() and any(output.iterdir()):
        raise ValueError(f"generated workspace directory must be empty: {output}")
    dependencies: dict[str, dict[str, Any]] = {}
    features: dict[str, set[str]] = {"default": set()}
    bins: dict[str, dict[str, Any]] = {}
    targets: list[FuzzTarget] = []
    build_script: str | None = None
    for fuzz_dir in sorted(path.resolve() for path in fuzz_dirs):
        with (fuzz_dir / "Cargo.toml").open("rb") as stream:
            manifest = tomllib.load(stream)
        # These need explicit handling if a future fuzz package adds them; never
        # silently omit build logic or platform-dependent prerequisites.
        unsupported = {"target", "build-dependencies", "patch", "replace", "profile"}
        if unsupported & manifest.keys() or "build" in manifest["package"]:
            raise ValueError(
                f"{fuzz_dir}: unsupported smoke-package build configuration"
            )
        build_path = fuzz_dir / "build.rs"
        if build_path.exists():
            # The codegen/g8r scripts are the same context-independent macOS
            # initializer-retention hook. Preserve it for the combined binaries;
            # refuse to silently discard or combine different build scripts.
            content = build_path.read_text(encoding="utf-8")
            if build_script is not None and build_script != content:
                raise ValueError(f"{fuzz_dir}: fuzz build scripts must match")
            build_script = content
        if manifest["package"].get("edition", "2015") != "2024":
            raise ValueError(f"{fuzz_dir}: smoke target sources must use edition 2024")
        for name, declaration in manifest.get("dependencies", {}).items():
            merge_dependency(dependencies, name, declaration, fuzz_dir)
        has_library = "lib" in manifest or (fuzz_dir / "src/lib.rs").is_file()
        package_name = manifest["package"]["name"]
        if has_library:
            # Let the aggregate default feature forward library defaults so
            # --no-default-features also applies to these support libraries.
            merge_dependency(
                dependencies,
                package_name,
                {"path": ".", "default-features": False},
                fuzz_dir,
            )
        for name, values in manifest.get("features", {}).items():
            features.setdefault(name, set()).update(values)
            if has_library:
                # Library code has its own cfg(feature) scope. Enable its
                # matching feature as well as the aggregate target's feature.
                features[name].add(f"{package_name}/{name}")
        for original in manifest.get("bin", []):
            target = dict(original)
            name = target["name"]
            if name in bins:
                raise ValueError(f"duplicate fuzz target name {name!r} in {fuzz_dir}")
            target["path"] = str((fuzz_dir / target["path"]).resolve())
            bins[name] = target
            targets.append(
                FuzzTarget(name, fuzz_dir, tuple(target.get("required-features", [])))
            )
    feature_lists = {name: sorted(values) for name, values in sorted(features.items())}
    lines = [
        GENERATED_HEADER,
        "# SPDX-License-Identifier: Apache-2.0",
        "[package]",
        'name = "xlsynth-fuzz-smoke"',
        # Like the PIR fuzz package, this unpublished package omits a version.
        # It must not become an independent entry in release-version sweeps.
        'edition = "2024"',
        "publish = false",
        "autobins = false",
        "[package.metadata]",
        "cargo-fuzz = true",
        "[workspace]",
        'resolver = "2"',
        "[dependencies]",
        *[
            f"{json.dumps(name)} = {toml_value(spec)}"
            for name, spec in sorted(dependencies.items())
        ],
        "[features]",
        *[
            f"{json.dumps(name)} = {toml_value(values)}"
            for name, values in feature_lists.items()
        ],
    ]
    for name, target in sorted(bins.items()):
        lines.append("[[bin]]")
        lines.extend(
            f"{json.dumps(key)} = {toml_value(value)}"
            for key, value in sorted(target.items())
        )
    text = "\n".join(lines) + "\n"
    output.mkdir(parents=True, exist_ok=True)
    path = output / "Cargo.toml"
    if not path.exists() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")
    build_path = output / "build.rs"
    if build_script is not None:
        if (
            not build_path.exists()
            or build_path.read_text(encoding="utf-8") != build_script
        ):
            build_path.write_text(build_script, encoding="utf-8")
    else:
        build_path.unlink(missing_ok=True)
    return SmokeWorkspace(output, targets, feature_lists)


def smoke_cache_outputs(
    repo_root: Path, workspace: Path, target_dir: Path, build_args: list[str]
) -> dict[str, str]:
    """Describe a build-only cache keyed by current manifests and build flags."""
    # Include local library manifests, not just the generated package. Changes
    # to transitive feature forwarding must also change the cache key. Git's
    # file list avoids reading old generated manifests beneath ignored outputs.
    listed = (
        subprocess.check_output(
            [
                "git",
                "ls-files",
                "--cached",
                "--others",
                "--exclude-standard",
                "-z",
                "--",
                "Cargo.toml",
                "**/Cargo.toml",
            ],
            cwd=repo_root,
        )
        .decode()
        .split("\0")
    )
    inputs = {repo_root / name for name in listed if name}
    inputs.update(
        [
            Path(__file__),
            Path(__file__).with_name("run_all_fuzz_tests.py"),
            workspace / "Cargo.toml",
            workspace / "Cargo.lock",
        ]
    )
    if (workspace / "build.rs").exists():
        inputs.add(workspace / "build.rs")
    digest = hashlib.sha256(json.dumps(build_args).encode())
    for path in sorted(inputs):
        digest.update(path.read_bytes())
        digest.update(b"\0")
    # rust-cache joins the output path to the workspace root, so supply a
    # relative mapping even when the workspace itself is outside the checkout.
    return {
        "cache-workspace": f"{workspace} -> {os.path.relpath(target_dir, workspace)}",
        "cache-key": digest.hexdigest(),
    }
