#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# A cached session may already have sourced our offline environment. Preparation
# must be allowed to fetch new dependencies before it enables offline mode again.
unset CARGO_NET_OFFLINE

# Ensure rustup environment is loaded if present
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

detect_platform() {
  if [ -f /etc/os-release ] && grep -q 'ID="rocky"' /etc/os-release; then
    echo "rocky8"
  else
    # This is the common case for Codex (Ubuntu/Debian based images).
    echo "ubuntu2004"
  fi
}

required_xls_tag() {
  /usr/bin/python3 "${repo_root}/scripts/get_required_libxls_dso_and_tools_release_tag.py"
}

platform="$(detect_platform)"
tag="$(required_xls_tag)"
tools_dir="${repo_root}/xlsynth_tools/${tag}/${platform}"

echo "==> Fetching XLS artifacts (tag: ${tag}, platform: ${platform})"
# Note: we use system python for this as we installed the python3-requests package earlier.
# This downloads:
# - libxls DSO (decompressed if the release asset is gzipped)
# - dslx_stdlib.tar.gz and unpacks it to "${tools_dir}/xls/dslx/stdlib"
/usr/bin/python3 "${repo_root}/scripts/download_release.py" -p "${platform}" -o "${tools_dir}" -v "${tag}"

dso_path="${tools_dir}/libxls-${platform}.so"
if [ ! -f "${dso_path}" ]; then
  echo "Expected to find a libxls DSO under ${tools_dir} but did not." 1>&2
  exit 1
fi

echo "==> Setting up environment variables"
export XLSYNTH_TOOLS="${tools_dir}"
export DSLX_STDLIB_PATH="$XLSYNTH_TOOLS/xls/dslx/stdlib"
export SLANG_PATH="/usr/local/bin/slang"
export PATH="$PATH:${repo_root}"
export XLS_DSO_PATH="${dso_path}"
# Build scripts are host executables too; keep their loader path explicit rather
# than depending on a libxls installed globally by a previous setup.
export LD_LIBRARY_PATH="${tools_dir}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

[ -f "$XLS_DSO_PATH" ] && echo "DSO found OK"

echo "==> Persisting environment variables for subsequent commands"
ENV_SH="${HOME}/.xlsynth_codex_env.sh"
cat > "${ENV_SH}" <<EOF
# Generated by ${repo_root}/codex/sample_codex_maintenance_script.sh
if [ -f "\${HOME}/.cargo/env" ]; then
  source "\${HOME}/.cargo/env"
fi
export XLSYNTH_TOOLS=$(printf '%q' "${XLSYNTH_TOOLS}")
export DSLX_STDLIB_PATH=$(printf '%q' "${DSLX_STDLIB_PATH}")
export SLANG_PATH=$(printf '%q' "${SLANG_PATH}")
export XLS_DSO_PATH=$(printf '%q' "${XLS_DSO_PATH}")
export LD_LIBRARY_PATH=$(printf '%q' "${LD_LIBRARY_PATH}")
export CARGO_NET_OFFLINE=true
export PATH=\$PATH:$(printf '%q' "${repo_root}")
EOF

append_source_if_missing() {
  local shell_rc="$1"
  local source_line
  printf -v source_line 'source %q' "${ENV_SH}"
  touch "${shell_rc}"
  grep -qxF "${source_line}" "${shell_rc}" || echo "${source_line}" >> "${shell_rc}"
}

# Codex Web shells can be a bit inconsistent about what gets sourced; cover the common cases.
append_source_if_missing "${HOME}/.bashrc"
append_source_if_missing "${HOME}/.bash_profile"
append_source_if_missing "${HOME}/.profile"

echo "==> Prefetching all Cargo dependencies"
for manifest in Cargo.toml xlsynth-g8r/fuzz/Cargo.toml xlsynth-vastly/fuzz/Cargo.toml; do
  cargo fetch --manifest-path "${manifest}" --quiet
done

echo "==> Preparing pre-commit environments"
pre-commit install
pre-commit install-hooks

# Every Cargo workspace used below must be cached before invoking the hooks:
# several hooks pass --offline themselves, including on the very first run.
export CARGO_NET_OFFLINE=true

echo "==> Running pre-commit"
# This is a non-interactive environment; avoid failing on branch protection checks.
SKIP=no-commit-to-branch pre-commit run --all-files

echo "==> Building fuzz target (compile-only, to ensure it builds)"
cargo fuzz build --fuzz-dir xlsynth-g8r/fuzz --sanitizer none fuzz_gate_fn_roundtrip

echo "==> Pre-building workspace to run all build.rs scripts"
cargo build --workspace --all-targets --locked --features with-bitwuzla-system

echo "✅ Maintenance complete — you can now run 'cargo test --workspace --features with-bitwuzla-system --frozen'"
