#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# Ensure rustup environment is loaded if present
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

detect_platform() {
  if [ -f /etc/os-release ] && grep -q 'ID="rocky"' /etc/os-release; then
    echo "rocky8"
  else
    # This is the common case for Codex (Ubuntu/Debian based images).
    echo "ubuntu2004"
  fi
}

required_xls_tag() {
  /usr/bin/python3 "${repo_root}/scripts/get_required_xls_release_tag.py"
}

platform="$(detect_platform)"
tag="$(required_xls_tag)"
tools_dir="${repo_root}/xlsynth_tools"

echo "==> Fetching XLS artifacts (tag: ${tag}, platform: ${platform})"
# Note: we use system python for this as we installed the python3-requests package earlier.
# This downloads:
# - libxls DSO (decompressed if the release asset is gzipped)
# - dslx_stdlib.tar.gz and unpacks it to "${tools_dir}/xls/dslx/stdlib"
/usr/bin/python3 "${repo_root}/scripts/download_release.py" -p "${platform}" -o "${tools_dir}" -d -v "${tag}"

dso_path="$(ls "${tools_dir}"/libxls-*.so 2>/dev/null | head -n 1 || true)"
if [ -z "${dso_path}" ] || [ ! -f "${dso_path}" ]; then
  echo "Expected to find a libxls DSO under ${tools_dir} but did not." 1>&2
  exit 1
fi

echo "==> Running ldconfig"
if command -v sudo >/dev/null 2>&1; then
  # Best-effort: if we can install the DSO into /usr/lib, do so, since that
  # matches many system link setups. If not, we still set XLS_DSO_PATH below.
  if [ -w /usr/lib ]; then
    cp -fv "${dso_path}" /usr/lib/
    ldconfig || true
  else
    sudo cp -fv "${dso_path}" /usr/lib/ || true
    sudo ldconfig || true
  fi
else
  ldconfig || true
fi

echo "==> Setting up environment variables"
export XLSYNTH_TOOLS="${tools_dir}"
export DSLX_STDLIB_PATH="$XLSYNTH_TOOLS/xls/dslx/stdlib"
export SLANG_PATH="/usr/local/bin/slang"
export PATH="$PATH:${repo_root}"
export XLS_DSO_PATH="${dso_path}"

[ -f "$XLS_DSO_PATH" ] && echo "DSO found OK"

echo "==> Persisting environment variables for subsequent commands"
ENV_SH="${HOME}/.xlsynth_codex_env.sh"
cat > "${ENV_SH}" <<EOF
# Generated by ${repo_root}/codex/sample_codex_maintenance_script.sh
export XLSYNTH_TOOLS=$(printf '%q' "${XLSYNTH_TOOLS}")
export DSLX_STDLIB_PATH=$(printf '%q' "${DSLX_STDLIB_PATH}")
export SLANG_PATH=$(printf '%q' "${SLANG_PATH}")
export XLS_DSO_PATH=$(printf '%q' "${XLS_DSO_PATH}")
export CARGO_NET_OFFLINE=true
export PATH=\$PATH:$(printf '%q' "${repo_root}")
EOF

append_source_if_missing() {
  local shell_rc="$1"
  local source_line="source ${ENV_SH}"
  touch "${shell_rc}"
  grep -qxF "${source_line}" "${shell_rc}" || echo "${source_line}" >> "${shell_rc}"
}

# Codex Web shells can be a bit inconsistent about what gets sourced; cover the common cases.
append_source_if_missing "${HOME}/.bashrc"
append_source_if_missing "${HOME}/.bash_profile"
append_source_if_missing "${HOME}/.profile"

pre-commit install

echo "==> Running pre-commit"
# This is a non-interactive environment; avoid failing on branch protection checks.
SKIP=no-commit-to-branch pre-commit run --all-files

echo "==> Prefetching all Cargo dependencies"
cargo fetch --quiet

echo "==> Building fuzz target (compile-only, to ensure it builds)"
(
  cd xlsynth-g8r/fuzz
  cargo fetch --quiet
)
(
  cd xlsynth-g8r
  cargo fuzz build fuzz_gatify
)

echo "==> Pre-building workspace to run all build.rs scripts"
cargo build --workspace --all-targets --features=with-boolector-system --jobs $(nproc)

echo "==> Going offline (network locked)"
export CARGO_NET_OFFLINE=true

echo "✅ Maintenance complete — you can now run 'cargo test --workspace'"
