[package]
name = "xlsynth-test-helpers"
version = "0.69.0"
edition = "2024"
authors = ["Christopher D. Leary <cdleary@gmail.com>"]
description = "xlsynth test helpers"
license = "Apache-2.0"
repository = "https://github.com/xlsynth/xlsynth-crate"
documentation = "https://docs.rs/xlsynth"
homepage = "https://github.com/xlsynth/xlsynth-crate"

[lints]
workspace = true

[features]
default = []
iverilog-tests = []

[[test]]
name = "rtl_sim_iverilog_test"
required-features = ["iverilog-tests"]

[[test]]
name = "rtl_syntax_iverilog_test"
required-features = ["iverilog-tests"]

[dependencies]
slang-rs = "0.12.0"
tempfile = "3.20"
log = "0.4"
env_logger = "0.11"
xlsynth = { version = "0.69.0", path = "../xlsynth" }
xlsynth-prover = { version = "0.69.0", path = "../xlsynth-prover" }
arbitrary = { version = "1.3", features = ["derive"] }
pretty_assertions = "1.4.1"
libc = "0.2"

[dev-dependencies]
xlsynth-sys = { path = "../xlsynth-sys" }
cargo_metadata = "0.23"
toml = "0.5"
ureq = { version = "3", default-features = false, features = ["rustls"] }
serde_json = "1.0"
semver = "1.0"
