# SPDX-License-Identifier: Apache-2.0

name: Publish to crates.io
permissions:
  contents: write

on:
  push:
    tags:
      - "v*" # This will trigger the workflow on version tags like v1.0.0, v0.1.0, etc.

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # Fetch full history and all tags so gen_version_compat.py can inspect them.
          fetch-depth: 0

      - name: Check version numbers
        run: python scripts/bump_version_numbers.py check

      - name: Set up version variables
        id: version_vars
        run: |
          FULL_VERSION="${GITHUB_REF#refs/tags/}"
          echo "FULL_VERSION=$FULL_VERSION"
          VERSION_NO_V="${FULL_VERSION#v}"
          echo "VERSION_NO_V=$VERSION_NO_V"
          echo "::set-output name=version_no_v::$VERSION_NO_V"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NO_V"
          echo "MAJOR=$MAJOR MINOR=$MINOR PATCH=$PATCH"
          echo "::set-output name=patch::$PATCH"

      - name: Validate version matches
        run: |
          python3 scripts/check_version_is.py "${{ steps.version_vars.outputs.version_no_v }}"

      - name: Download xlsynth binaries
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python3 -V
          pip3 install --break-system-packages requests
          REQUIRED_TAG=$(python3 scripts/get_required_xls_release_tag.py)
          echo "Required XLS release tag: $REQUIRED_TAG"
          python3 scripts/download_release.py -p arm64 -o xlsynth_tools -v "$REQUIRED_TAG"

      - name: Install protobuf compiler
        run: |
          curl -L --retry 5 --retry-delay 2 --retry-connrefused -o protoc-29.1-osx-aarch_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v29.1/protoc-29.1-osx-aarch_64.zip
          unzip protoc-29.1-osx-aarch_64.zip -d protoc
          sudo mv protoc/bin/protoc /usr/local/bin/protoc
          sudo mv protoc /tmp/
          sudo mv protoc-*.zip /tmp/
          protoc --version

      - name: Install Icarus Verilog
        run: |
          brew update
          brew install icarus-verilog

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Build and test
        run: |
          export XLSYNTH_TOOLS=`realpath xlsynth_tools`
          cargo test --workspace

      - name: Install Python dependencies for polling script
        run: python3 -m pip install --break-system-packages requests

      - name: Publish xlsynth-sys to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cd xlsynth-sys
          cargo publish --token $CARGO_REGISTRY_TOKEN

      - name: Wait for xlsynth-sys on crates.io
        run: python3 scripts/sleep_until_version_seen.py xlsynth-sys "${{ steps.version_vars.outputs.version_no_v }}"

      - name: Publish xlsynth
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cd xlsynth
          cargo publish --token $CARGO_REGISTRY_TOKEN

      - name: Wait for xlsynth on crates.io
        run: python3 scripts/sleep_until_version_seen.py xlsynth "${{ steps.version_vars.outputs.version_no_v }}"

      - name: Publish xlsynth-test-helpers
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cd xlsynth-test-helpers
          cargo publish --token $CARGO_REGISTRY_TOKEN

      - name: Wait for xlsynth-test-helpers on crates.io
        run: python3 scripts/sleep_until_version_seen.py xlsynth-test-helpers "${{ steps.version_vars.outputs.version_no_v }}"

      - name: Publish xlsynth-pir
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cd xlsynth-pir
          cargo publish --token $CARGO_REGISTRY_TOKEN

      - name: Wait for xlsynth-pir on crates.io
        run: python3 scripts/sleep_until_version_seen.py xlsynth-pir "${{ steps.version_vars.outputs.version_no_v }}"

      - name: Publish xlsynth-g8r
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cd xlsynth-g8r
          cargo publish --token $CARGO_REGISTRY_TOKEN

      - name: Wait for xlsynth-g8r on crates.io
        run: python3 scripts/sleep_until_version_seen.py xlsynth-g8r "${{ steps.version_vars.outputs.version_no_v }}"

      - name: Publish xlsynth-estimator
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cd xlsynth-estimator
          cargo publish --token $CARGO_REGISTRY_TOKEN

      - name: Wait for xlsynth-estimator on crates.io
        run: python3 scripts/sleep_until_version_seen.py xlsynth-estimator "${{ steps.version_vars.outputs.version_no_v }}"

      - name: Publish xlsynth-prover
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cd xlsynth-prover
          cargo publish --token $CARGO_REGISTRY_TOKEN

      - name: Wait for xlsynth-prover on crates.io
        run: python3 scripts/sleep_until_version_seen.py xlsynth-prover "${{ steps.version_vars.outputs.version_no_v }}"

      - name: Publish xlsynth-driver
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cd xlsynth-driver
          cargo publish --token $CARGO_REGISTRY_TOKEN

      # No wait needed after the last crate published in the sequence

      - name: Bump version numbers (minor bump for mainline release)
        if: ${{ success() && steps.version_vars.outputs.patch == '0' }}
        run: |
          cargo clean
          python scripts/bump_version_numbers.py bump-minor
          cargo generate-lockfile

      - name: Validate post-bump version equals expected next minor
        if: ${{ success() && steps.version_vars.outputs.patch == '0' }}
        run: |
          VERSION_NO_V="${{ steps.version_vars.outputs.version_no_v }}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NO_V"
          NEXT_MINOR=$((MINOR+1))
          EXPECTED_NEXT="${MAJOR}.${NEXT_MINOR}.0"
          echo "Expecting post-bump version: $EXPECTED_NEXT"
          python3 scripts/check_version_is.py "$EXPECTED_NEXT"

      - name: Commit bumped version numbers
        if: ${{ success() && steps.version_vars.outputs.patch == '0' }}
        run: |
          git config user.name "github-actions"
          git config user.email "xlsynth-github-actions@xlsynth.org"
          git add $(find . -type f -name "Cargo.toml")
          git commit -m "Bump version numbers after successful publish"
          git push "https://${GITHUB_ACTOR}:${MY_PAT}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main

      - name: Update version compatibility docs
        if: ${{ success() && steps.version_vars.outputs.patch == '0' }}
        run: |
          python3 scripts/gen_version_compat.py

      - name: Commit version metadata update
        if: ${{ success() && steps.version_vars.outputs.patch == '0' }}
        run: |
          git config user.name "github-actions"
          git config user.email "xlsynth-github-actions@xlsynth.org"
          git add docs/version_metadata.md generated_version_compat.json
          git commit -m "Update version metadata after successful publish"
          git push "https://${GITHUB_ACTOR}:${MY_PAT}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
